// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ObjectAPIVersion.
const (
	ObjectAPIVersionKubernetesCrossplaneIoV1Alpha1 ObjectAPIVersion = "kubernetes.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ObjectAPIVersion enum.
func (e ObjectAPIVersion) Valid() bool {
	switch e {
	case ObjectAPIVersionKubernetesCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ObjectKind.
const (
	ObjectKindObject ObjectKind = "Object"
)

// Valid indicates whether the value is a known member of the ObjectKind enum.
func (e ObjectKind) Valid() bool {
	switch e {
	case ObjectKindObject:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecDeletionPolicy.
const (
	ObjectSpecDeletionPolicyDelete ObjectSpecDeletionPolicy = "Delete"
	ObjectSpecDeletionPolicyOrphan ObjectSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the ObjectSpecDeletionPolicy enum.
func (e ObjectSpecDeletionPolicy) Valid() bool {
	switch e {
	case ObjectSpecDeletionPolicyDelete:
		return true
	case ObjectSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecManagementPolicy.
const (
	ObjectSpecManagementPolicyDefault             ObjectSpecManagementPolicy = "Default"
	ObjectSpecManagementPolicyObserve             ObjectSpecManagementPolicy = "Observe"
	ObjectSpecManagementPolicyObserveCreateUpdate ObjectSpecManagementPolicy = "ObserveCreateUpdate"
	ObjectSpecManagementPolicyObserveDelete       ObjectSpecManagementPolicy = "ObserveDelete"
)

// Valid indicates whether the value is a known member of the ObjectSpecManagementPolicy enum.
func (e ObjectSpecManagementPolicy) Valid() bool {
	switch e {
	case ObjectSpecManagementPolicyDefault:
		return true
	case ObjectSpecManagementPolicyObserve:
		return true
	case ObjectSpecManagementPolicyObserveCreateUpdate:
		return true
	case ObjectSpecManagementPolicyObserveDelete:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecProviderConfigRefPolicyResolution.
const (
	ObjectSpecProviderConfigRefPolicyResolutionOptional ObjectSpecProviderConfigRefPolicyResolution = "Optional"
	ObjectSpecProviderConfigRefPolicyResolutionRequired ObjectSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the ObjectSpecProviderConfigRefPolicyResolution enum.
func (e ObjectSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case ObjectSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case ObjectSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecProviderConfigRefPolicyResolve.
const (
	ObjectSpecProviderConfigRefPolicyResolveAlways       ObjectSpecProviderConfigRefPolicyResolve = "Always"
	ObjectSpecProviderConfigRefPolicyResolveIfNotPresent ObjectSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the ObjectSpecProviderConfigRefPolicyResolve enum.
func (e ObjectSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case ObjectSpecProviderConfigRefPolicyResolveAlways:
		return true
	case ObjectSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecProviderRefPolicyResolution.
const (
	ObjectSpecProviderRefPolicyResolutionOptional ObjectSpecProviderRefPolicyResolution = "Optional"
	ObjectSpecProviderRefPolicyResolutionRequired ObjectSpecProviderRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the ObjectSpecProviderRefPolicyResolution enum.
func (e ObjectSpecProviderRefPolicyResolution) Valid() bool {
	switch e {
	case ObjectSpecProviderRefPolicyResolutionOptional:
		return true
	case ObjectSpecProviderRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecProviderRefPolicyResolve.
const (
	ObjectSpecProviderRefPolicyResolveAlways       ObjectSpecProviderRefPolicyResolve = "Always"
	ObjectSpecProviderRefPolicyResolveIfNotPresent ObjectSpecProviderRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the ObjectSpecProviderRefPolicyResolve enum.
func (e ObjectSpecProviderRefPolicyResolve) Valid() bool {
	switch e {
	case ObjectSpecProviderRefPolicyResolveAlways:
		return true
	case ObjectSpecProviderRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecReadinessPolicy.
const (
	ObjectSpecReadinessPolicyAllTrue          ObjectSpecReadinessPolicy = "AllTrue"
	ObjectSpecReadinessPolicyDeriveFromObject ObjectSpecReadinessPolicy = "DeriveFromObject"
	ObjectSpecReadinessPolicySuccessfulCreate ObjectSpecReadinessPolicy = "SuccessfulCreate"
)

// Valid indicates whether the value is a known member of the ObjectSpecReadinessPolicy enum.
func (e ObjectSpecReadinessPolicy) Valid() bool {
	switch e {
	case ObjectSpecReadinessPolicyAllTrue:
		return true
	case ObjectSpecReadinessPolicyDeriveFromObject:
		return true
	case ObjectSpecReadinessPolicySuccessfulCreate:
		return true
	default:
		return false
	}
}

// IoCrossplaneKubernetesV1Alpha1Object A Object is an provider Kubernetes API type
//
// Deprecated: v1alpha1.Object is deprecated in favor of v1alpha2.Object
type IoCrossplaneKubernetesV1Alpha1Object = Object

// ObjectAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ObjectAPIVersion string

// ObjectKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ObjectKind string

// ObjectSpecConnectionDetailsItem ConnectionDetail represents an entry in the connection secret for an Object
type ObjectSpecConnectionDetailsItem struct {
	// APIVersion API version of the referent.
	APIVersion *string `json:"apiVersion,omitempty"`

	// FieldPath If referring to a piece of an object instead of an entire object, this string
	// should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].
	// For example, if the object reference is to a container within a pod, this would take on a value like:
	// "spec.containers{name}" (where "name" refers to the name of the container that triggered
	// the event) or if no container name is specified "spec.containers[2]" (container with
	// index 2 in this pod). This syntax is chosen only to have some well-defined way of
	// referencing a part of an object.
	FieldPath *string `json:"fieldPath,omitempty"`

	// Kind Kind of the referent.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
	Namespace *string `json:"namespace,omitempty"`

	// ResourceVersion Specific resourceVersion to which this reference is made, if any.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
	ResourceVersion       *string `json:"resourceVersion,omitempty"`
	ToConnectionSecretKey *string `json:"toConnectionSecretKey,omitempty"`

	// UID UID of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
	UID *string `json:"uid,omitempty"`
}

// ObjectSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicy
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type ObjectSpecDeletionPolicy string

// ObjectSpecForProvider ObjectParameters are the configurable fields of a Object.
type ObjectSpecForProvider struct {
	// Manifest Raw JSON representation of the kubernetes object to be created.
	Manifest *map[string]interface{} `json:"manifest,omitempty"`
}

// ObjectSpecManagementPolicy A ManagementPolicy determines what should happen to the underlying external
// resource when a managed resource is created, updated, deleted, or observed.
type ObjectSpecManagementPolicy string

// ObjectSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type ObjectSpecProviderConfigRefPolicyResolution string

// ObjectSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type ObjectSpecProviderConfigRefPolicyResolve string

// ObjectSpecProviderConfigRefPolicy Policies for referencing.
type ObjectSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *ObjectSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *ObjectSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// ObjectSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type ObjectSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *ObjectSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// ObjectSpecProviderRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type ObjectSpecProviderRefPolicyResolution string

// ObjectSpecProviderRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type ObjectSpecProviderRefPolicyResolve string

// ObjectSpecProviderRefPolicy Policies for referencing.
type ObjectSpecProviderRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *ObjectSpecProviderRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *ObjectSpecProviderRefPolicyResolve `json:"resolve,omitempty"`
}

// ObjectSpecProviderRef ProviderReference specifies the provider that will be used to create,
// observe, update, and delete this managed resource.
//
// Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
type ObjectSpecProviderRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *ObjectSpecProviderRefPolicy `json:"policy,omitempty"`
}

// ObjectSpecReadinessPolicy Policy defines how the Object's readiness condition should be computed.
type ObjectSpecReadinessPolicy string

// ObjectSpecReadiness Readiness defines how the object's readiness condition should be computed,
// if not specified it will be considered ready as soon as the underlying external
// resource is considered up-to-date.
type ObjectSpecReadiness struct {
	// Policy Policy defines how the Object's readiness condition should be computed.
	Policy *ObjectSpecReadinessPolicy `json:"policy,omitempty"`
}

// ObjectSpecReferencesItemDependsOn DependsOn is used to declare dependency on other Object or arbitrary
// Kubernetes resource.
type ObjectSpecReferencesItemDependsOn struct {
	// APIVersion APIVersion of the referenced object.
	APIVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object.
	Namespace *string `json:"namespace,omitempty"`
}

// ObjectSpecReferencesItemPatchesFrom PatchesFrom is used to declare dependency on other Object or arbitrary
// Kubernetes resource, and also patch fields from this object.
type ObjectSpecReferencesItemPatchesFrom struct {
	// APIVersion APIVersion of the referenced object.
	APIVersion *string `json:"apiVersion,omitempty"`

	// FieldPath FieldPath is the path of the field on the resource whose value is to be
	// used as input.
	FieldPath *string `json:"fieldPath,omitempty"`

	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object.
	Namespace *string `json:"namespace,omitempty"`
}

// ObjectSpecReferencesItem Reference refers to an Object or arbitrary Kubernetes resource and optionally
// patch values from that resource to the current Object.
type ObjectSpecReferencesItem struct {
	// DependsOn DependsOn is used to declare dependency on other Object or arbitrary
	// Kubernetes resource.
	DependsOn *ObjectSpecReferencesItemDependsOn `json:"dependsOn,omitempty"`

	// PatchesFrom PatchesFrom is used to declare dependency on other Object or arbitrary
	// Kubernetes resource, and also patch fields from this object.
	PatchesFrom *ObjectSpecReferencesItemPatchesFrom `json:"patchesFrom,omitempty"`

	// ToFieldPath ToFieldPath is the path of the field on the resource whose value will
	// be changed with the result of transforms. Leave empty if you'd like to
	// propagate to the same path as patchesFrom.fieldPath.
	ToFieldPath *string `json:"toFieldPath,omitempty"`
}

// ObjectSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
// This field is planned to be replaced in a future release in favor of
// PublishConnectionDetailsTo. Currently, both could be set independently
// and connection details would be published to both without affecting
// each other.
type ObjectSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ObjectSpec A ObjectSpec defines the desired state of a Object.
type ObjectSpec struct {
	ConnectionDetails *[]ObjectSpecConnectionDetailsItem `json:"connectionDetails,omitempty"`

	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicy
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *ObjectSpecDeletionPolicy `json:"deletionPolicy,omitempty"`

	// ForProvider ObjectParameters are the configurable fields of a Object.
	ForProvider *ObjectSpecForProvider `json:"forProvider,omitempty"`

	// ManagementPolicy A ManagementPolicy determines what should happen to the underlying external
	// resource when a managed resource is created, updated, deleted, or observed.
	ManagementPolicy *ObjectSpecManagementPolicy `json:"managementPolicy,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *ObjectSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// ProviderRef ProviderReference specifies the provider that will be used to create,
	// observe, update, and delete this managed resource.
	//
	// Deprecated: Please use ProviderConfigReference, i.e. `providerConfigRef`
	ProviderRef *ObjectSpecProviderRef `json:"providerRef,omitempty"`

	// Readiness Readiness defines how the object's readiness condition should be computed,
	// if not specified it will be considered ready as soon as the underlying external
	// resource is considered up-to-date.
	Readiness  *ObjectSpecReadiness        `json:"readiness,omitempty"`
	References *[]ObjectSpecReferencesItem `json:"references,omitempty"`

	// Watch Watch enables watching the referenced or managed kubernetes resources.
	//
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless "watches" feature gate is enabled, and may be changed or removed
	// without notice.
	Watch *bool `json:"watch,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	// This field is planned to be replaced in a future release in favor of
	// PublishConnectionDetailsTo. Currently, both could be set independently
	// and connection details would be published to both without affecting
	// each other.
	WriteConnectionSecretToRef *ObjectSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// ObjectStatusAtProvider ObjectObservation are the observable fields of a Object.
type ObjectStatusAtProvider struct {
	// Manifest Raw JSON representation of the remote object.
	Manifest *map[string]interface{} `json:"manifest,omitempty"`
}

// ObjectStatusConditionsItem A Condition that may apply to a resource.
type ObjectStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ObjectStatus A ObjectStatus represents the observed state of a Object.
type ObjectStatus struct {
	// AtProvider ObjectObservation are the observable fields of a Object.
	AtProvider *ObjectStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]ObjectStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Object A Object is an provider Kubernetes API type
//
// Deprecated: v1alpha1.Object is deprecated in favor of v1alpha2.Object
type Object struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ObjectAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ObjectKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec A ObjectSpec defines the desired state of a Object.
	Spec *ObjectSpec `json:"spec,omitempty"`

	// Status A ObjectStatus represents the observed state of a Object.
	Status *ObjectStatus `json:"status,omitempty"`
}

// IoCrossplaneKubernetesV1Alpha1ObjectList ObjectList is a list of Object
type IoCrossplaneKubernetesV1Alpha1ObjectList = ObjectList

// ObjectList ObjectList is a list of Object
type ObjectList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of objects. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneKubernetesV1Alpha1Object `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
