// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ClusterProviderConfigAPIVersion.
const (
	ClusterProviderConfigAPIVersionKubernetesMCrossplaneIoV1Alpha1 ClusterProviderConfigAPIVersion = "kubernetes.m.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ClusterProviderConfigAPIVersion enum.
func (e ClusterProviderConfigAPIVersion) Valid() bool {
	switch e {
	case ClusterProviderConfigAPIVersionKubernetesMCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ClusterProviderConfigKind.
const (
	ClusterProviderConfigKindClusterProviderConfig ClusterProviderConfigKind = "ClusterProviderConfig"
)

// Valid indicates whether the value is a known member of the ClusterProviderConfigKind enum.
func (e ClusterProviderConfigKind) Valid() bool {
	switch e {
	case ClusterProviderConfigKindClusterProviderConfig:
		return true
	default:
		return false
	}
}

// Defines values for ClusterProviderConfigSpecCredentialsSource.
const (
	ClusterProviderConfigSpecCredentialsSourceEnvironment      ClusterProviderConfigSpecCredentialsSource = "Environment"
	ClusterProviderConfigSpecCredentialsSourceFilesystem       ClusterProviderConfigSpecCredentialsSource = "Filesystem"
	ClusterProviderConfigSpecCredentialsSourceInjectedIdentity ClusterProviderConfigSpecCredentialsSource = "InjectedIdentity"
	ClusterProviderConfigSpecCredentialsSourceNone             ClusterProviderConfigSpecCredentialsSource = "None"
	ClusterProviderConfigSpecCredentialsSourceSecret           ClusterProviderConfigSpecCredentialsSource = "Secret"
)

// Valid indicates whether the value is a known member of the ClusterProviderConfigSpecCredentialsSource enum.
func (e ClusterProviderConfigSpecCredentialsSource) Valid() bool {
	switch e {
	case ClusterProviderConfigSpecCredentialsSourceEnvironment:
		return true
	case ClusterProviderConfigSpecCredentialsSourceFilesystem:
		return true
	case ClusterProviderConfigSpecCredentialsSourceInjectedIdentity:
		return true
	case ClusterProviderConfigSpecCredentialsSourceNone:
		return true
	case ClusterProviderConfigSpecCredentialsSourceSecret:
		return true
	default:
		return false
	}
}

// Defines values for ClusterProviderConfigSpecIdentitySource.
const (
	ClusterProviderConfigSpecIdentitySourceEnvironment      ClusterProviderConfigSpecIdentitySource = "Environment"
	ClusterProviderConfigSpecIdentitySourceFilesystem       ClusterProviderConfigSpecIdentitySource = "Filesystem"
	ClusterProviderConfigSpecIdentitySourceInjectedIdentity ClusterProviderConfigSpecIdentitySource = "InjectedIdentity"
	ClusterProviderConfigSpecIdentitySourceNone             ClusterProviderConfigSpecIdentitySource = "None"
	ClusterProviderConfigSpecIdentitySourceSecret           ClusterProviderConfigSpecIdentitySource = "Secret"
)

// Valid indicates whether the value is a known member of the ClusterProviderConfigSpecIdentitySource enum.
func (e ClusterProviderConfigSpecIdentitySource) Valid() bool {
	switch e {
	case ClusterProviderConfigSpecIdentitySourceEnvironment:
		return true
	case ClusterProviderConfigSpecIdentitySourceFilesystem:
		return true
	case ClusterProviderConfigSpecIdentitySourceInjectedIdentity:
		return true
	case ClusterProviderConfigSpecIdentitySourceNone:
		return true
	case ClusterProviderConfigSpecIdentitySourceSecret:
		return true
	default:
		return false
	}
}

// Defines values for ClusterProviderConfigSpecIdentityType.
const (
	ClusterProviderConfigSpecIdentityTypeAWSWebIdentityCredentials        ClusterProviderConfigSpecIdentityType = "AWSWebIdentityCredentials"
	ClusterProviderConfigSpecIdentityTypeAzureServicePrincipalCredentials ClusterProviderConfigSpecIdentityType = "AzureServicePrincipalCredentials"
	ClusterProviderConfigSpecIdentityTypeAzureWorkloadIdentityCredentials ClusterProviderConfigSpecIdentityType = "AzureWorkloadIdentityCredentials"
	ClusterProviderConfigSpecIdentityTypeGoogleApplicationCredentials     ClusterProviderConfigSpecIdentityType = "GoogleApplicationCredentials"
	ClusterProviderConfigSpecIdentityTypeNebiusServiceAccountCredentials  ClusterProviderConfigSpecIdentityType = "NebiusServiceAccountCredentials"
	ClusterProviderConfigSpecIdentityTypeUpboundTokens                    ClusterProviderConfigSpecIdentityType = "UpboundTokens"
)

// Valid indicates whether the value is a known member of the ClusterProviderConfigSpecIdentityType enum.
func (e ClusterProviderConfigSpecIdentityType) Valid() bool {
	switch e {
	case ClusterProviderConfigSpecIdentityTypeAWSWebIdentityCredentials:
		return true
	case ClusterProviderConfigSpecIdentityTypeAzureServicePrincipalCredentials:
		return true
	case ClusterProviderConfigSpecIdentityTypeAzureWorkloadIdentityCredentials:
		return true
	case ClusterProviderConfigSpecIdentityTypeGoogleApplicationCredentials:
		return true
	case ClusterProviderConfigSpecIdentityTypeNebiusServiceAccountCredentials:
		return true
	case ClusterProviderConfigSpecIdentityTypeUpboundTokens:
		return true
	default:
		return false
	}
}

// IoCrossplaneMKubernetesV1Alpha1ClusterProviderConfig A ClusterProviderConfig configures a Kubernetes provider.
type IoCrossplaneMKubernetesV1Alpha1ClusterProviderConfig = ClusterProviderConfig

// ClusterProviderConfigAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ClusterProviderConfigAPIVersion string

// ClusterProviderConfigKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ClusterProviderConfigKind string

// ClusterProviderConfigSpecCredentialsEnv Env is a reference to an environment variable that contains credentials
// that must be used to connect to the provider.
type ClusterProviderConfigSpecCredentialsEnv struct {
	// Name Name is the name of an environment variable.
	Name *string `json:"name,omitempty"`
}

// ClusterProviderConfigSpecCredentialsFs Fs is a reference to a filesystem location that contains credentials that
// must be used to connect to the provider.
type ClusterProviderConfigSpecCredentialsFs struct {
	// Path Path is a filesystem path.
	Path *string `json:"path,omitempty"`
}

// ClusterProviderConfigSpecCredentialsSecretRef A SecretRef is a reference to a secret key that contains the credentials
// that must be used to connect to the provider.
type ClusterProviderConfigSpecCredentialsSecretRef struct {
	// Key The key to select.
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ClusterProviderConfigSpecCredentialsSource Source of the provider credentials.
type ClusterProviderConfigSpecCredentialsSource string

// ClusterProviderConfigSpecCredentials Credentials used to connect to the Kubernetes API. Typically a
// kubeconfig file. Use InjectedIdentity for in-cluster config.
type ClusterProviderConfigSpecCredentials struct {
	// Env Env is a reference to an environment variable that contains credentials
	// that must be used to connect to the provider.
	Env *ClusterProviderConfigSpecCredentialsEnv `json:"env,omitempty"`

	// Fs Fs is a reference to a filesystem location that contains credentials that
	// must be used to connect to the provider.
	Fs *ClusterProviderConfigSpecCredentialsFs `json:"fs,omitempty"`

	// SecretRef A SecretRef is a reference to a secret key that contains the credentials
	// that must be used to connect to the provider.
	SecretRef *ClusterProviderConfigSpecCredentialsSecretRef `json:"secretRef,omitempty"`

	// Source Source of the provider credentials.
	Source *ClusterProviderConfigSpecCredentialsSource `json:"source,omitempty"`
}

// ClusterProviderConfigSpecIdentityEnv Env is a reference to an environment variable that contains credentials
// that must be used to connect to the provider.
type ClusterProviderConfigSpecIdentityEnv struct {
	// Name Name is the name of an environment variable.
	Name *string `json:"name,omitempty"`
}

// ClusterProviderConfigSpecIdentityFs Fs is a reference to a filesystem location that contains credentials that
// must be used to connect to the provider.
type ClusterProviderConfigSpecIdentityFs struct {
	// Path Path is a filesystem path.
	Path *string `json:"path,omitempty"`
}

// ClusterProviderConfigSpecIdentitySecretRef A SecretRef is a reference to a secret key that contains the credentials
// that must be used to connect to the provider.
type ClusterProviderConfigSpecIdentitySecretRef struct {
	// Key The key to select.
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ClusterProviderConfigSpecIdentitySource Source of the provider credentials.
type ClusterProviderConfigSpecIdentitySource string

// ClusterProviderConfigSpecIdentityType Type of identity.
type ClusterProviderConfigSpecIdentityType string

// ClusterProviderConfigSpecIdentity Identity used to authenticate to the Kubernetes API. The identity
// credentials can be used to supplement kubeconfig 'credentials', for
// example by configuring a bearer token source such as OAuth.
type ClusterProviderConfigSpecIdentity struct {
	// Env Env is a reference to an environment variable that contains credentials
	// that must be used to connect to the provider.
	Env *ClusterProviderConfigSpecIdentityEnv `json:"env,omitempty"`

	// Fs Fs is a reference to a filesystem location that contains credentials that
	// must be used to connect to the provider.
	Fs *ClusterProviderConfigSpecIdentityFs `json:"fs,omitempty"`

	// SecretRef A SecretRef is a reference to a secret key that contains the credentials
	// that must be used to connect to the provider.
	SecretRef *ClusterProviderConfigSpecIdentitySecretRef `json:"secretRef,omitempty"`

	// Source Source of the provider credentials.
	Source *ClusterProviderConfigSpecIdentitySource `json:"source,omitempty"`

	// Type Type of identity.
	Type *ClusterProviderConfigSpecIdentityType `json:"type,omitempty"`
}

// ClusterProviderConfigSpec A ProviderConfigSpec defines the desired state of a ProviderConfig.
type ClusterProviderConfigSpec struct {
	// Credentials Credentials used to connect to the Kubernetes API. Typically a
	// kubeconfig file. Use InjectedIdentity for in-cluster config.
	Credentials *ClusterProviderConfigSpecCredentials `json:"credentials,omitempty"`

	// Identity Identity used to authenticate to the Kubernetes API. The identity
	// credentials can be used to supplement kubeconfig 'credentials', for
	// example by configuring a bearer token source such as OAuth.
	Identity *ClusterProviderConfigSpecIdentity `json:"identity,omitempty"`
}

// ClusterProviderConfigStatusConditionsItem A Condition that may apply to a resource.
type ClusterProviderConfigStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ClusterProviderConfigStatus A ProviderConfigStatus reflects the observed state of a ProviderConfig.
type ClusterProviderConfigStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]ClusterProviderConfigStatusConditionsItem `json:"conditions,omitempty"`

	// Users Users of this provider configuration.
	Users *int64 `json:"users,omitempty"`
}

// ClusterProviderConfig A ClusterProviderConfig configures a Kubernetes provider.
type ClusterProviderConfig struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ClusterProviderConfigAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ClusterProviderConfigKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec A ProviderConfigSpec defines the desired state of a ProviderConfig.
	Spec *ClusterProviderConfigSpec `json:"spec,omitempty"`

	// Status A ProviderConfigStatus reflects the observed state of a ProviderConfig.
	Status *ClusterProviderConfigStatus `json:"status,omitempty"`
}

// IoCrossplaneMKubernetesV1Alpha1ClusterProviderConfigList ClusterProviderConfigList is a list of ClusterProviderConfig
type IoCrossplaneMKubernetesV1Alpha1ClusterProviderConfigList = ClusterProviderConfigList

// ClusterProviderConfigList ClusterProviderConfigList is a list of ClusterProviderConfig
type ClusterProviderConfigList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of clusterproviderconfigs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneMKubernetesV1Alpha1ClusterProviderConfig `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
