// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ObjectAPIVersion.
const (
	ObjectAPIVersionKubernetesMCrossplaneIoV1Alpha1 ObjectAPIVersion = "kubernetes.m.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ObjectAPIVersion enum.
func (e ObjectAPIVersion) Valid() bool {
	switch e {
	case ObjectAPIVersionKubernetesMCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ObjectKind.
const (
	ObjectKindObject ObjectKind = "Object"
)

// Valid indicates whether the value is a known member of the ObjectKind enum.
func (e ObjectKind) Valid() bool {
	switch e {
	case ObjectKindObject:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecForProviderDeletionPropagationPolicy.
const (
	ObjectSpecForProviderDeletionPropagationPolicyBackground ObjectSpecForProviderDeletionPropagationPolicy = "Background"
	ObjectSpecForProviderDeletionPropagationPolicyForeground ObjectSpecForProviderDeletionPropagationPolicy = "Foreground"
	ObjectSpecForProviderDeletionPropagationPolicyOrphan     ObjectSpecForProviderDeletionPropagationPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the ObjectSpecForProviderDeletionPropagationPolicy enum.
func (e ObjectSpecForProviderDeletionPropagationPolicy) Valid() bool {
	switch e {
	case ObjectSpecForProviderDeletionPropagationPolicyBackground:
		return true
	case ObjectSpecForProviderDeletionPropagationPolicyForeground:
		return true
	case ObjectSpecForProviderDeletionPropagationPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecManagementPoliciesItem.
const (
	ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItem               ObjectSpecManagementPoliciesItem = "*"
	ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemCreate         ObjectSpecManagementPoliciesItem = "Create"
	ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemDelete         ObjectSpecManagementPoliciesItem = "Delete"
	ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemLateInitialize ObjectSpecManagementPoliciesItem = "LateInitialize"
	ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemObserve        ObjectSpecManagementPoliciesItem = "Observe"
	ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemUpdate         ObjectSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the ObjectSpecManagementPoliciesItem enum.
func (e ObjectSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItem:
		return true
	case ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemCreate:
		return true
	case ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemDelete:
		return true
	case ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemLateInitialize:
		return true
	case ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemObserve:
		return true
	case ObjectSpecManagementPoliciesItemObjectSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for ObjectSpecReadinessPolicy.
const (
	ObjectSpecReadinessPolicyAllTrue            ObjectSpecReadinessPolicy = "AllTrue"
	ObjectSpecReadinessPolicyDeriveFromCelQuery ObjectSpecReadinessPolicy = "DeriveFromCelQuery"
	ObjectSpecReadinessPolicyDeriveFromObject   ObjectSpecReadinessPolicy = "DeriveFromObject"
	ObjectSpecReadinessPolicySuccessfulCreate   ObjectSpecReadinessPolicy = "SuccessfulCreate"
)

// Valid indicates whether the value is a known member of the ObjectSpecReadinessPolicy enum.
func (e ObjectSpecReadinessPolicy) Valid() bool {
	switch e {
	case ObjectSpecReadinessPolicyAllTrue:
		return true
	case ObjectSpecReadinessPolicyDeriveFromCelQuery:
		return true
	case ObjectSpecReadinessPolicyDeriveFromObject:
		return true
	case ObjectSpecReadinessPolicySuccessfulCreate:
		return true
	default:
		return false
	}
}

// IoCrossplaneMKubernetesV1Alpha1Object A Object is an provider Kubernetes API type
type IoCrossplaneMKubernetesV1Alpha1Object = Object

// ObjectAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ObjectAPIVersion string

// ObjectKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ObjectKind string

// ObjectSpecConnectionDetailsItem ConnectionDetail represents an entry in the connection secret for an Object
type ObjectSpecConnectionDetailsItem struct {
	// APIVersion API version of the referent.
	APIVersion *string `json:"apiVersion,omitempty"`

	// FieldPath If referring to a piece of an object instead of an entire object, this string
	// should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].
	// For example, if the object reference is to a container within a pod, this would take on a value like:
	// "spec.containers{name}" (where "name" refers to the name of the container that triggered
	// the event) or if no container name is specified "spec.containers[2]" (container with
	// index 2 in this pod). This syntax is chosen only to have some well-defined way of
	// referencing a part of an object.
	FieldPath *string `json:"fieldPath,omitempty"`

	// Kind Kind of the referent.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
	Namespace *string `json:"namespace,omitempty"`

	// ResourceVersion Specific resourceVersion to which this reference is made, if any.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
	ResourceVersion       *string `json:"resourceVersion,omitempty"`
	ToConnectionSecretKey *string `json:"toConnectionSecretKey,omitempty"`

	// UID UID of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
	UID *string `json:"uid,omitempty"`
}

// ObjectSpecForProviderDeletionPropagationPolicy Deletion policy for created kubernetes object, defaults to Background
type ObjectSpecForProviderDeletionPropagationPolicy string

// ObjectSpecForProvider ObjectParameters are the configurable fields of a Object.
type ObjectSpecForProvider struct {
	// DeletionPropagationPolicy Deletion policy for created kubernetes object, defaults to Background
	DeletionPropagationPolicy *ObjectSpecForProviderDeletionPropagationPolicy `json:"deletionPropagationPolicy,omitempty"`

	// Manifest Raw JSON representation of the kubernetes object to be created.
	Manifest *map[string]interface{} `json:"manifest,omitempty"`
}

// ObjectSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type ObjectSpecManagementPoliciesItem string

// ObjectSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type ObjectSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// ObjectSpecReadinessPolicy Policy defines how the Object's readiness condition should be computed.
type ObjectSpecReadinessPolicy string

// ObjectSpecReadiness Readiness defines how the object's readiness condition should be computed,
// if not specified it will be considered ready as soon as the underlying external
// resource is considered up-to-date.
type ObjectSpecReadiness struct {
	// CelQuery CelQuery defines a cel query to evaluate the readiness. The
	// observed object is passed to the cel query with the word `object`.
	// Cel macros are available to be used, see https://github.com/google/cel-spec/blob/master/doc/langdef.md#macros
	// for more information.
	// Examples:
	//  `object.status.isReady == true`: checks for a boolean field called isReady on status.
	//  `object.status.conditions.all(x, x.status == "True")` mimics the behavior of the AllTrue readiness policy
	//  `object.status.conditions.exists(c, c.type == "condition1" && c.status == "True" )` checks just one condition
	CelQuery *string `json:"celQuery,omitempty"`

	// Policy Policy defines how the Object's readiness condition should be computed.
	Policy *ObjectSpecReadinessPolicy `json:"policy,omitempty"`
}

// ObjectSpecReferencesItemDependsOn DependsOn is used to declare dependency on other Object or arbitrary
// Kubernetes resource.
type ObjectSpecReferencesItemDependsOn struct {
	// APIVersion APIVersion of the referenced object.
	APIVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object.
	Namespace *string `json:"namespace,omitempty"`
}

// ObjectSpecReferencesItemPatchesFrom PatchesFrom is used to declare dependency on other Object or arbitrary
// Kubernetes resource, and also patch fields from this object.
type ObjectSpecReferencesItemPatchesFrom struct {
	// APIVersion APIVersion of the referenced object.
	APIVersion *string `json:"apiVersion,omitempty"`

	// FieldPath FieldPath is the path of the field on the resource whose value is to be
	// used as input.
	FieldPath *string `json:"fieldPath,omitempty"`

	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object.
	Namespace *string `json:"namespace,omitempty"`
}

// ObjectSpecReferencesItem Reference refers to an Object or arbitrary Kubernetes resource and optionally
// patch values from that resource to the current Object.
type ObjectSpecReferencesItem struct {
	// DependsOn DependsOn is used to declare dependency on other Object or arbitrary
	// Kubernetes resource.
	DependsOn *ObjectSpecReferencesItemDependsOn `json:"dependsOn,omitempty"`

	// PatchesFrom PatchesFrom is used to declare dependency on other Object or arbitrary
	// Kubernetes resource, and also patch fields from this object.
	PatchesFrom *ObjectSpecReferencesItemPatchesFrom `json:"patchesFrom,omitempty"`

	// ToFieldPath ToFieldPath is the path of the field on the resource whose value will
	// be changed with the result of transforms. Leave empty if you'd like to
	// propagate to the same path as patchesFrom.fieldPath.
	ToFieldPath *string `json:"toFieldPath,omitempty"`
}

// ObjectSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type ObjectSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// ObjectSpec A ObjectSpec defines the desired state of a Object.
type ObjectSpec struct {
	ConnectionDetails *[]ObjectSpecConnectionDetailsItem `json:"connectionDetails,omitempty"`

	// ForProvider ObjectParameters are the configurable fields of a Object.
	ForProvider *ObjectSpecForProvider `json:"forProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]ObjectSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *ObjectSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// Readiness Readiness defines how the object's readiness condition should be computed,
	// if not specified it will be considered ready as soon as the underlying external
	// resource is considered up-to-date.
	Readiness  *ObjectSpecReadiness        `json:"readiness,omitempty"`
	References *[]ObjectSpecReferencesItem `json:"references,omitempty"`

	// Watch Watch enables watching the referenced or managed kubernetes resources.
	//
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless "watches" feature gate is enabled, and may be changed or removed
	// without notice.
	Watch *bool `json:"watch,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *ObjectSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// ObjectStatusAtProvider ObjectObservation are the observable fields of a Object.
type ObjectStatusAtProvider struct {
	// Manifest Raw JSON representation of the remote object.
	Manifest *map[string]interface{} `json:"manifest,omitempty"`
}

// ObjectStatusConditionsItem A Condition that may apply to a resource.
type ObjectStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ObjectStatus A ObjectStatus represents the observed state of a Object.
type ObjectStatus struct {
	// AtProvider ObjectObservation are the observable fields of a Object.
	AtProvider *ObjectStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]ObjectStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// Object A Object is an provider Kubernetes API type
type Object struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ObjectAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ObjectKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec A ObjectSpec defines the desired state of a Object.
	Spec *ObjectSpec `json:"spec,omitempty"`

	// Status A ObjectStatus represents the observed state of a Object.
	Status *ObjectStatus `json:"status,omitempty"`
}

// IoCrossplaneMKubernetesV1Alpha1ObjectList ObjectList is a list of Object
type IoCrossplaneMKubernetesV1Alpha1ObjectList = ObjectList

// ObjectList ObjectList is a list of Object
type ObjectList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of objects. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneMKubernetesV1Alpha1Object `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
