// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ObservedObjectCollectionAPIVersion.
const (
	ObservedObjectCollectionAPIVersionKubernetesMCrossplaneIoV1Alpha1 ObservedObjectCollectionAPIVersion = "kubernetes.m.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ObservedObjectCollectionAPIVersion enum.
func (e ObservedObjectCollectionAPIVersion) Valid() bool {
	switch e {
	case ObservedObjectCollectionAPIVersionKubernetesMCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ObservedObjectCollectionKind.
const (
	ObservedObjectCollectionKindObservedObjectCollection ObservedObjectCollectionKind = "ObservedObjectCollection"
)

// Valid indicates whether the value is a known member of the ObservedObjectCollectionKind enum.
func (e ObservedObjectCollectionKind) Valid() bool {
	switch e {
	case ObservedObjectCollectionKindObservedObjectCollection:
		return true
	default:
		return false
	}
}

// IoCrossplaneMKubernetesV1Alpha1ObservedObjectCollection A ObservedObjectCollection is a provider Kubernetes API type
type IoCrossplaneMKubernetesV1Alpha1ObservedObjectCollection = ObservedObjectCollection

// ObservedObjectCollectionAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ObservedObjectCollectionAPIVersion string

// ObservedObjectCollectionKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ObservedObjectCollectionKind string

// ObservedObjectCollectionSpecObjectTemplateMetadata Objects metadata
type ObservedObjectCollectionSpecObjectTemplateMetadata struct {
	// Annotations Annotations of an object
	Annotations *map[string]string `json:"annotations,omitempty"`

	// Labels Labels of an object
	Labels *map[string]string `json:"labels,omitempty"`
}

// ObservedObjectCollectionSpecObjectTemplate Template when defined is used for creating Object instances
type ObservedObjectCollectionSpecObjectTemplate struct {
	// Metadata Objects metadata
	Metadata *ObservedObjectCollectionSpecObjectTemplateMetadata `json:"metadata,omitempty"`
}

// ObservedObjectCollectionSpecObserveObjectsSelectorMatchExpressionsItem A label selector requirement is a selector that contains values, a key, and an operator that
// relates the key and values.
type ObservedObjectCollectionSpecObserveObjectsSelectorMatchExpressionsItem struct {
	// Key key is the label key that the selector applies to.
	Key *string `json:"key,omitempty"`

	// Operator operator represents a key's relationship to a set of values.
	// Valid operators are In, NotIn, Exists and DoesNotExist.
	Operator *string `json:"operator,omitempty"`

	// Values values is an array of string values. If the operator is In or NotIn,
	// the values array must be non-empty. If the operator is Exists or DoesNotExist,
	// the values array must be empty. This array is replaced during a strategic
	// merge patch.
	Values *[]string `json:"values,omitempty"`
}

// ObservedObjectCollectionSpecObserveObjectsSelector Selector defines the criteria for including objects into the collection
type ObservedObjectCollectionSpecObserveObjectsSelector struct {
	// MatchExpressions matchExpressions is a list of label selector requirements. The requirements are ANDed.
	MatchExpressions *[]ObservedObjectCollectionSpecObserveObjectsSelectorMatchExpressionsItem `json:"matchExpressions,omitempty"`

	// MatchLabels matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
	// map is equivalent to an element of matchExpressions, whose key field is "key", the
	// operator is "In", and the values array contains only "value". The requirements are ANDed.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// ObservedObjectCollectionSpecObserveObjects ObserveObjects declares what criteria object need to fulfil
// to become a member of this collection
type ObservedObjectCollectionSpecObserveObjects struct {
	// APIVersion APIVersion of objects that should be matched by the selector
	APIVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind of objects that should be matched by the selector
	Kind *string `json:"kind,omitempty"`

	// Namespace Namespace where to look for objects.
	// If omitted, search is performed across all namespaces.
	// For cluster-scoped objects, omit it.
	Namespace *string `json:"namespace,omitempty"`

	// Selector Selector defines the criteria for including objects into the collection
	Selector *ObservedObjectCollectionSpecObserveObjectsSelector `json:"selector,omitempty"`
}

// ObservedObjectCollectionSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type ObservedObjectCollectionSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// ObservedObjectCollectionSpec ObservedObjectCollectionSpec defines the desired state of ObservedObjectCollection
type ObservedObjectCollectionSpec struct {
	// ObjectTemplate Template when defined is used for creating Object instances
	ObjectTemplate *ObservedObjectCollectionSpecObjectTemplate `json:"objectTemplate,omitempty"`

	// ObserveObjects ObserveObjects declares what criteria object need to fulfil
	// to become a member of this collection
	ObserveObjects *ObservedObjectCollectionSpecObserveObjects `json:"observeObjects,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *ObservedObjectCollectionSpecProviderConfigRef `json:"providerConfigRef,omitempty"`
}

// ObservedObjectCollectionStatusConditionsItem A Condition that may apply to a resource.
type ObservedObjectCollectionStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ObservedObjectCollectionStatus ObservedObjectCollectionStatus represents the observed state of a ObservedObjectCollection
type ObservedObjectCollectionStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]ObservedObjectCollectionStatusConditionsItem `json:"conditions,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// MembershipLabel MembershipLabel is the label set on each member of this collection
	// and can be used for fetching them.
	MembershipLabel *map[string]string `json:"membershipLabel,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// ObservedObjectCollection A ObservedObjectCollection is a provider Kubernetes API type
type ObservedObjectCollection struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ObservedObjectCollectionAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ObservedObjectCollectionKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec ObservedObjectCollectionSpec defines the desired state of ObservedObjectCollection
	Spec *ObservedObjectCollectionSpec `json:"spec,omitempty"`

	// Status ObservedObjectCollectionStatus represents the observed state of a ObservedObjectCollection
	Status *ObservedObjectCollectionStatus `json:"status,omitempty"`
}

// IoCrossplaneMKubernetesV1Alpha1ObservedObjectCollectionList ObservedObjectCollectionList is a list of ObservedObjectCollection
type IoCrossplaneMKubernetesV1Alpha1ObservedObjectCollectionList = ObservedObjectCollectionList

// ObservedObjectCollectionList ObservedObjectCollectionList is a list of ObservedObjectCollection
type ObservedObjectCollectionList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of observedobjectcollections. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneMKubernetesV1Alpha1ObservedObjectCollection `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
