apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    type: database-backup
  name: database-backup-cnpg
spec:
  compositeTypeRef:
    apiVersion: database.kaonix.inc.fr/v1alpha1
    kind: DatabaseBackup
  mode: Pipeline
  pipeline:
  - step: render-templates
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      options:
        - missingkey=error
      inline:
        template: |
          {{ $id := .observed.composite.resource.spec.id }}
          {{ $backupName := printf "%s-backup-manual" $id }}
          {{ if index .observed.composite.resource.spec "backupName" }}
          {{ $backupName = index .observed.composite.resource.spec "backupName" }}
          {{ end }}
          {{ $namespace := dig "metadata" "namespace" "default" .observed.composite.resource }}
          {{ $backup := getComposedResource . "backup" }}
          ---
          apiVersion: postgresql.cnpg.io/v1
          kind: Backup
          metadata:
            name: {{ $backupName }}
            namespace: {{ $namespace }}
            annotations:
              {{ setResourceNameAnnotation "backup" }}
            {{ if and $backup (eq (dig "status" "phase" "" $backup) "completed") }}
              gotemplating.fn.crossplane.io/ready: "True"
          {{ end }}
          spec:
            cluster:
              name: {{ $id }}
            method: volumeSnapshot
          ---
          apiVersion: database.kaonix.inc.fr/v1alpha1
          kind: DatabaseBackup
          status:
            name: {{ $backupName }}
          {{ if $backup }}
            phase: {{ dig "status" "phase" "" $backup | quote }}
            startedAt: {{ dig "status" "startedAt" "" $backup | quote }}
            completionTime: {{ dig "status" "stoppedAt" "" $backup | quote }}
            error: {{ dig "status" "error" "" $backup | quote }}
          {{ end }}
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: function-auto-ready
