// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ProviderConfigUsageAPIVersion.
const (
	ProviderConfigUsageAPIVersionHelmMCrossplaneIoV1Beta1 ProviderConfigUsageAPIVersion = "helm.m.crossplane.io/v1beta1"
)

// Valid indicates whether the value is a known member of the ProviderConfigUsageAPIVersion enum.
func (e ProviderConfigUsageAPIVersion) Valid() bool {
	switch e {
	case ProviderConfigUsageAPIVersionHelmMCrossplaneIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigUsageKind.
const (
	ProviderConfigUsageKindProviderConfigUsage ProviderConfigUsageKind = "ProviderConfigUsage"
)

// Valid indicates whether the value is a known member of the ProviderConfigUsageKind enum.
func (e ProviderConfigUsageKind) Valid() bool {
	switch e {
	case ProviderConfigUsageKindProviderConfigUsage:
		return true
	default:
		return false
	}
}

// IoCrossplaneMHelmV1Beta1ProviderConfigUsage A ProviderConfigUsage indicates that a resource is using a ProviderConfig.
type IoCrossplaneMHelmV1Beta1ProviderConfigUsage = ProviderConfigUsage

// ProviderConfigUsageAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ProviderConfigUsageAPIVersion string

// ProviderConfigUsageKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ProviderConfigUsageKind string

// ProviderConfigUsageProviderConfigRef ProviderConfigReference to the provider config being used.
type ProviderConfigUsageProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// ProviderConfigUsageResourceRef ResourceReference to the managed resource using the provider config.
type ProviderConfigUsageResourceRef struct {
	// APIVersion APIVersion of the referenced object.
	APIVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// UID UID of the referenced object.
	UID *string `json:"uid,omitempty"`
}

// ProviderConfigUsage A ProviderConfigUsage indicates that a resource is using a ProviderConfig.
type ProviderConfigUsage struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ProviderConfigUsageAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ProviderConfigUsageKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// ProviderConfigRef ProviderConfigReference to the provider config being used.
	ProviderConfigRef *ProviderConfigUsageProviderConfigRef `json:"providerConfigRef,omitempty"`

	// ResourceRef ResourceReference to the managed resource using the provider config.
	ResourceRef *ProviderConfigUsageResourceRef `json:"resourceRef,omitempty"`
}

// IoCrossplaneMHelmV1Beta1ProviderConfigUsageList ProviderConfigUsageList is a list of ProviderConfigUsage
type IoCrossplaneMHelmV1Beta1ProviderConfigUsageList = ProviderConfigUsageList

// ProviderConfigUsageList ProviderConfigUsageList is a list of ProviderConfigUsage
type ProviderConfigUsageList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of providerconfigusages. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneMHelmV1Beta1ProviderConfigUsage `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
