// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for GoTemplateAPIVersion.
const (
	GoTemplateAPIVersionGotemplatingFnCrossplaneIoV1Beta1 GoTemplateAPIVersion = "gotemplating.fn.crossplane.io/v1beta1"
)

// Valid indicates whether the value is a known member of the GoTemplateAPIVersion enum.
func (e GoTemplateAPIVersion) Valid() bool {
	switch e {
	case GoTemplateAPIVersionGotemplatingFnCrossplaneIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for GoTemplateKind.
const (
	GoTemplateKindGoTemplate GoTemplateKind = "GoTemplate"
)

// Valid indicates whether the value is a known member of the GoTemplateKind enum.
func (e GoTemplateKind) Valid() bool {
	switch e {
	case GoTemplateKindGoTemplate:
		return true
	default:
		return false
	}
}

// IoCrossplaneFnGotemplatingV1Beta1GoTemplate A GoTemplate is used to provide templates to this Function.
type IoCrossplaneFnGotemplatingV1Beta1GoTemplate = GoTemplate

// GoTemplateAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type GoTemplateAPIVersion string

// GoTemplateDelims Template delimiters
type GoTemplateDelims struct {
	// Left Template start characters
	Left *string `json:"left,omitempty"`

	// Right Template end characters
	Right *string `json:"right,omitempty"`
}

// GoTemplateEnvironment Environment is the key that defines the location of the templates in the environment
type GoTemplateEnvironment struct {
	Key *string `json:"key,omitempty"`
}

// GoTemplateFileSystem FileSystem is the folder path where the templates are located
type GoTemplateFileSystem struct {
	DirPath *string `json:"dirPath,omitempty"`
}

// GoTemplateInline Inline is the inline form input of the templates
type GoTemplateInline struct {
	Template  *string   `json:"template,omitempty"`
	Templates *[]string `json:"templates,omitempty"`
}

// GoTemplateKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type GoTemplateKind string

// GoTemplate A GoTemplate is used to provide templates to this Function.
type GoTemplate struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *GoTemplateAPIVersion `json:"apiVersion,omitempty"`

	// Delims Template delimiters
	Delims *GoTemplateDelims `json:"delims,omitempty"`

	// Environment Environment is the key that defines the location of the templates in the environment
	Environment *GoTemplateEnvironment `json:"environment,omitempty"`

	// FileSystem FileSystem is the folder path where the templates are located
	FileSystem *GoTemplateFileSystem `json:"fileSystem,omitempty"`

	// Inline Inline is the inline form input of the templates
	Inline *GoTemplateInline `json:"inline,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *GoTemplateKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Options Options to set for the template engine. Valid options are documented at https://pkg.go.dev/text/template#Template.Option
	Options *[]string `json:"options,omitempty"`

	// Source Source specifies the different types of input sources that can be used with this function
	Source *string `json:"source,omitempty"`
}

// IoCrossplaneFnGotemplatingV1Beta1GoTemplateList GoTemplateList is a list of GoTemplate
type IoCrossplaneFnGotemplatingV1Beta1GoTemplateList = GoTemplateList

// GoTemplateList GoTemplateList is a list of GoTemplate
type GoTemplateList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of gotemplates. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneFnGotemplatingV1Beta1GoTemplate `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
