apiVersion: ops.crossplane.io/v1alpha1
kind: Operation
metadata:
  name: pause-orders-database
spec:
  mode: Pipeline
  pipeline:
  - step: pause
    functionRef:
      name: function-pause
    requirements:
      requiredResources:
      - requirementName: target
        apiVersion: database.kaonix.inc.fr/v1alpha1
        kind: PostgreSQL
        name: orders
        namespace: platform
    input:
      apiVersion: function-pause.fn.kaonix.com/v1beta1
      kind: Input
      spec:
        target:
          apiVersion: database.kaonix.inc.fr/v1alpha1
          kind: PostgreSQL
          name: orders
          namespace: platform
        paused: true
