# generated by datamodel-codegen:
#   filename:  workdir/autoready_fn_crossplane_io_v1beta1_input.yaml

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

from .....k8s.apimachinery.pkg.apis.meta import v1


class Input(BaseModel):
    apiVersion: Literal['autoready.fn.crossplane.io/v1beta1'] | None = (
        'autoready.fn.crossplane.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    celHealthCheckCustomization: dict[str, str] | None = None
    """
    CELHealthCheckCustomization is a inline map of CEL health check customizations
    Inline customizations are merged with from Context customizations
    and take precedence over Context-provided healthchecks allowing for granular overwrites
    """
    celHealthCheckCustomizationFrom: str | None = None
    """
    CELHealthCheckCustomizationFrom is a reference to fetch CEL health check customizations from context
    """
    kind: Literal['Input'] | None = 'Input'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    ttl: str | None = '1m0s'
    """
    TTL for which a response can be cached in time.Duration format
    """


class InputList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Input]
    """
    List of inputs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """