// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for AppAPIVersion.
const (
	AppAPIVersionKaonixComV1Alpha1 AppAPIVersion = "kaonix.com/v1alpha1"
)

// Valid indicates whether the value is a known member of the AppAPIVersion enum.
func (e AppAPIVersion) Valid() bool {
	switch e {
	case AppAPIVersionKaonixComV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for AppKind.
const (
	AppKindApp AppKind = "App"
)

// Valid indicates whether the value is a known member of the AppKind enum.
func (e AppKind) Valid() bool {
	switch e {
	case AppKindApp:
		return true
	default:
		return false
	}
}

// Defines values for AppSpecCrossplaneCompositionUpdatePolicy.
const (
	AppSpecCrossplaneCompositionUpdatePolicyAutomatic AppSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	AppSpecCrossplaneCompositionUpdatePolicyManual    AppSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// Valid indicates whether the value is a known member of the AppSpecCrossplaneCompositionUpdatePolicy enum.
func (e AppSpecCrossplaneCompositionUpdatePolicy) Valid() bool {
	switch e {
	case AppSpecCrossplaneCompositionUpdatePolicyAutomatic:
		return true
	case AppSpecCrossplaneCompositionUpdatePolicyManual:
		return true
	default:
		return false
	}
}

// ComKaonixV1Alpha1App defines model for com.kaonix.v1alpha1.App.
type ComKaonixV1Alpha1App = App

// AppAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type AppAPIVersion string

// AppKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type AppKind string

// AppSpecCrossplaneCompositionRef defines model for .
type AppSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// AppSpecCrossplaneCompositionRevisionRef defines model for .
type AppSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// AppSpecCrossplaneCompositionRevisionSelector defines model for .
type AppSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// AppSpecCrossplaneCompositionSelector defines model for .
type AppSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// AppSpecCrossplaneCompositionUpdatePolicy defines model for com.kaonix.v1alpha1.App.spec.crossplane.compositionUpdatePolicy.
type AppSpecCrossplaneCompositionUpdatePolicy string

// AppSpecCrossplaneResourceRefsItem defines model for .
type AppSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// AppSpecCrossplane Configures how Crossplane will reconcile this composite resource
type AppSpecCrossplane struct {
	CompositionRef              *AppSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *AppSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *AppSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *AppSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *AppSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]AppSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// AppSpecParameters defines model for .
type AppSpecParameters struct {
	// Image The container image of the application.
	Image *string `json:"image,omitempty"`

	// Namespace The namespace to deploy into.
	Namespace *string `json:"namespace,omitempty"`

	// Port The application port.
	Port *int `json:"port,omitempty"`
}

// AppSpec defines model for .
type AppSpec struct {
	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *AppSpecCrossplane `json:"crossplane,omitempty"`

	// ID Unique identifier for this application.
	ID         *string            `json:"id,omitempty"`
	Parameters *AppSpecParameters `json:"parameters,omitempty"`
}

// AppStatusConditionsItem defines model for .
type AppStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// AppStatus defines model for .
type AppStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]AppStatusConditionsItem `json:"conditions,omitempty"`
}

// App defines model for .
type App struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *AppAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *AppKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec     *AppSpec           `json:"spec,omitempty"`
	Status   *AppStatus         `json:"status,omitempty"`
}

// ComKaonixV1Alpha1AppList AppList is a list of App
type ComKaonixV1Alpha1AppList = AppList

// AppList AppList is a list of App
type AppList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of apps. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]ComKaonixV1Alpha1App `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
