// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for DatabaseAPIVersion.
const (
	DatabaseAPIVersionKaonixComV1Alpha1 DatabaseAPIVersion = "kaonix.com/v1alpha1"
)

// Valid indicates whether the value is a known member of the DatabaseAPIVersion enum.
func (e DatabaseAPIVersion) Valid() bool {
	switch e {
	case DatabaseAPIVersionKaonixComV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseKind.
const (
	DatabaseKindDatabase DatabaseKind = "Database"
)

// Valid indicates whether the value is a known member of the DatabaseKind enum.
func (e DatabaseKind) Valid() bool {
	switch e {
	case DatabaseKindDatabase:
		return true
	default:
		return false
	}
}

// Defines values for DatabaseSpecCrossplaneCompositionUpdatePolicy.
const (
	DatabaseSpecCrossplaneCompositionUpdatePolicyAutomatic DatabaseSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	DatabaseSpecCrossplaneCompositionUpdatePolicyManual    DatabaseSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// Valid indicates whether the value is a known member of the DatabaseSpecCrossplaneCompositionUpdatePolicy enum.
func (e DatabaseSpecCrossplaneCompositionUpdatePolicy) Valid() bool {
	switch e {
	case DatabaseSpecCrossplaneCompositionUpdatePolicyAutomatic:
		return true
	case DatabaseSpecCrossplaneCompositionUpdatePolicyManual:
		return true
	default:
		return false
	}
}

// ComKaonixV1Alpha1Database defines model for com.kaonix.v1alpha1.Database.
type ComKaonixV1Alpha1Database = Database

// DatabaseAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type DatabaseAPIVersion string

// DatabaseKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type DatabaseKind string

// DatabaseSpecCrossplaneCompositionRef defines model for .
type DatabaseSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// DatabaseSpecCrossplaneCompositionRevisionRef defines model for .
type DatabaseSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// DatabaseSpecCrossplaneCompositionRevisionSelector defines model for .
type DatabaseSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// DatabaseSpecCrossplaneCompositionSelector defines model for .
type DatabaseSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// DatabaseSpecCrossplaneCompositionUpdatePolicy defines model for com.kaonix.v1alpha1.Database.spec.crossplane.compositionUpdatePolicy.
type DatabaseSpecCrossplaneCompositionUpdatePolicy string

// DatabaseSpecCrossplaneResourceRefsItem defines model for .
type DatabaseSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// DatabaseSpecCrossplane Configures how Crossplane will reconcile this composite resource
type DatabaseSpecCrossplane struct {
	CompositionRef              *DatabaseSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *DatabaseSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *DatabaseSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *DatabaseSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *DatabaseSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]DatabaseSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// DatabaseSpecParameters defines model for .
type DatabaseSpecParameters struct {
	// Database The name of the database to create.
	Database *string `json:"database,omitempty"`

	// Instances Number of PostgreSQL instances (replicas).
	Instances *int `json:"instances,omitempty"`

	// Namespace The namespace for the database resources.
	Namespace *string `json:"namespace,omitempty"`

	// Size Predefined size preset. Supported values are `small`, `medium`, and `large`.
	Size *string `json:"size,omitempty"`

	// StorageSize Explicit PVC storage size (e.g., 1Gi). Overrides the size preset when set.
	StorageSize *string `json:"storageSize,omitempty"`

	// Version PostgreSQL major version (e.g., 13, 14, 15, 16).
	Version *string `json:"version,omitempty"`
}

// DatabaseSpec defines model for .
type DatabaseSpec struct {
	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *DatabaseSpecCrossplane `json:"crossplane,omitempty"`

	// ID Unique identifier for this database.
	ID         *string                 `json:"id,omitempty"`
	Parameters *DatabaseSpecParameters `json:"parameters,omitempty"`
}

// DatabaseStatusConditionsItem defines model for .
type DatabaseStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// DatabaseStatus defines model for .
type DatabaseStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]DatabaseStatusConditionsItem `json:"conditions,omitempty"`

	// DBName Name of the database.
	DBName *string `json:"dbName,omitempty"`

	// Host Internal Kubernetes Service address.
	Host *string `json:"host,omitempty"`

	// Port PostgreSQL port.
	Port *int `json:"port,omitempty"`

	// SecretName Name of the Secret containing credentials.
	SecretName *string `json:"secretName,omitempty"`
}

// Database defines model for .
type Database struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *DatabaseAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *DatabaseKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec     *DatabaseSpec      `json:"spec,omitempty"`
	Status   *DatabaseStatus    `json:"status,omitempty"`
}

// ComKaonixV1Alpha1DatabaseList DatabaseList is a list of Database
type ComKaonixV1Alpha1DatabaseList = DatabaseList

// DatabaseList DatabaseList is a list of Database
type DatabaseList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of databases. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]ComKaonixV1Alpha1Database `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
