// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for NetworkAPIVersion.
const (
	NetworkAPIVersionKaonixComV1Alpha1 NetworkAPIVersion = "kaonix.com/v1alpha1"
)

// Valid indicates whether the value is a known member of the NetworkAPIVersion enum.
func (e NetworkAPIVersion) Valid() bool {
	switch e {
	case NetworkAPIVersionKaonixComV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for NetworkKind.
const (
	NetworkKindNetwork NetworkKind = "Network"
)

// Valid indicates whether the value is a known member of the NetworkKind enum.
func (e NetworkKind) Valid() bool {
	switch e {
	case NetworkKindNetwork:
		return true
	default:
		return false
	}
}

// Defines values for NetworkSpecCrossplaneCompositionUpdatePolicy.
const (
	NetworkSpecCrossplaneCompositionUpdatePolicyAutomatic NetworkSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	NetworkSpecCrossplaneCompositionUpdatePolicyManual    NetworkSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// Valid indicates whether the value is a known member of the NetworkSpecCrossplaneCompositionUpdatePolicy enum.
func (e NetworkSpecCrossplaneCompositionUpdatePolicy) Valid() bool {
	switch e {
	case NetworkSpecCrossplaneCompositionUpdatePolicyAutomatic:
		return true
	case NetworkSpecCrossplaneCompositionUpdatePolicyManual:
		return true
	default:
		return false
	}
}

// ComKaonixV1Alpha1Network defines model for com.kaonix.v1alpha1.Network.
type ComKaonixV1Alpha1Network = Network

// NetworkAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type NetworkAPIVersion string

// NetworkKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type NetworkKind string

// NetworkSpecCrossplaneCompositionRef defines model for .
type NetworkSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// NetworkSpecCrossplaneCompositionRevisionRef defines model for .
type NetworkSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// NetworkSpecCrossplaneCompositionRevisionSelector defines model for .
type NetworkSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// NetworkSpecCrossplaneCompositionSelector defines model for .
type NetworkSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// NetworkSpecCrossplaneCompositionUpdatePolicy defines model for com.kaonix.v1alpha1.Network.spec.crossplane.compositionUpdatePolicy.
type NetworkSpecCrossplaneCompositionUpdatePolicy string

// NetworkSpecCrossplaneResourceRefsItem defines model for .
type NetworkSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// NetworkSpecCrossplane Configures how Crossplane will reconcile this composite resource
type NetworkSpecCrossplane struct {
	CompositionRef              *NetworkSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *NetworkSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *NetworkSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *NetworkSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *NetworkSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]NetworkSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// NetworkSpecParametersIngress Ingress configuration (optional).
type NetworkSpecParametersIngress struct {
	// Host The hostname for the Ingress rule.
	Host *string `json:"host,omitempty"`

	// Path The path for the Ingress rule.
	Path *string `json:"path,omitempty"`

	// TLSSecret TLS secret name for HTTPS. If empty, no TLS.
	TLSSecret *string `json:"tlsSecret,omitempty"`
}

// NetworkSpecParametersNetworkPolicy NetworkPolicy configuration (optional).
type NetworkSpecParametersNetworkPolicy struct {
	// Egress Allowed egress destinations as CIDR blocks.
	Egress *[]string `json:"egress,omitempty"`

	// Ingress Allowed ingress sources as CIDR blocks.
	Ingress *[]string `json:"ingress,omitempty"`
}

// NetworkSpecParametersPortsItem defines model for .
type NetworkSpecParametersPortsItem struct {
	// Port The port to expose.
	Port *int `json:"port,omitempty"`

	// Protocol The protocol (TCP or UDP).
	Protocol *string `json:"protocol,omitempty"`

	// TargetPort The port on the target pod. Defaults to port.
	TargetPort *int `json:"targetPort,omitempty"`
}

// NetworkSpecParameters defines model for .
type NetworkSpecParameters struct {
	// AppName The name of the target application (used for selector matching).
	AppName *string `json:"appName,omitempty"`

	// DNS External DNS name (creates an ExternalName service).
	DNS *string `json:"dns,omitempty"`

	// Ingress Ingress configuration (optional).
	Ingress *NetworkSpecParametersIngress `json:"ingress,omitempty"`

	// Namespace The namespace of the target application.
	Namespace *string `json:"namespace,omitempty"`

	// NetworkPolicy NetworkPolicy configuration (optional).
	NetworkPolicy *NetworkSpecParametersNetworkPolicy `json:"networkPolicy,omitempty"`

	// Ports List of port mappings to expose.
	Ports *[]NetworkSpecParametersPortsItem `json:"ports,omitempty"`
}

// NetworkSpec defines model for .
type NetworkSpec struct {
	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *NetworkSpecCrossplane `json:"crossplane,omitempty"`

	// ID Unique identifier for this network configuration.
	ID         *string                `json:"id,omitempty"`
	Parameters *NetworkSpecParameters `json:"parameters,omitempty"`
}

// NetworkStatusConditionsItem defines model for .
type NetworkStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// NetworkStatus defines model for .
type NetworkStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]NetworkStatusConditionsItem `json:"conditions,omitempty"`

	// IngressHost The Ingress host.
	IngressHost *string `json:"ingressHost,omitempty"`

	// NetworkPolicyName The name of the created NetworkPolicy.
	NetworkPolicyName *string `json:"networkPolicyName,omitempty"`

	// ServiceName The name of the created Service.
	ServiceName *string `json:"serviceName,omitempty"`
}

// Network defines model for .
type Network struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *NetworkAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *NetworkKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec     *NetworkSpec       `json:"spec,omitempty"`
	Status   *NetworkStatus     `json:"status,omitempty"`
}

// ComKaonixV1Alpha1NetworkList NetworkList is a list of Network
type ComKaonixV1Alpha1NetworkList = NetworkList

// NetworkList NetworkList is a list of Network
type NetworkList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of networks. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]ComKaonixV1Alpha1Network `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
