apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: apps.kaonix.com
spec:
  claimNames:
    kind: AppClaim
    plural: appclaims
  defaultCompositeDeletePolicy: Background
  defaultCompositionRef:
    name: app-frontend
  defaultCompositionUpdatePolicy: Automatic
  group: kaonix.com
  names:
    kind: App
    plural: apps
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.host
      name: host
      type: string
    name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              id:
                description: ID of this application that other objects will use to
                  refer to it.
                type: string
              parameters:
                properties:
                  db:
                    properties:
                      size:
                        default: small
                        description: Supported sizes are `small`, `medium`, and `large`.
                          This field is used only with the Composition `app-backend-db-google`.
                        type: string
                      version:
                        description: The DB version depends on the DB type and versions
                          available in the selected provider. This field is used only
                          with the `app-backend-db-google` Composition.
                        type: string
                    type: object
                  dbSecret:
                    properties:
                      name:
                        description: The name of the Secret with DB authentication
                          (used only with compositions with the label location=remote).
                          This field is used only with the `app-backend-db*` Compositions.
                        type: string
                      namespace:
                        description: The Namespace with the Secret with DB authentication
                          (used only with compositions with the label location=remote).  This
                          field is used only with the `app-backend-db*` Compositions.
                        type: string
                    type: object
                  host:
                    description: The host address of the application
                    type: string
                  image:
                    description: The container image of the application
                    type: string
                  kubernetesProviderConfigName:
                    default: default
                    description: The name of the Kubernetes provider config (used
                      only with compositions with the label location=remote).
                    type: string
                  namespace:
                    default: production
                    description: The namespace
                    type: string
                  port:
                    default: 80
                    description: The application port
                    type: integer
                required:
                - image
                type: object
            required:
            - id
            - parameters
            type: object
          status:
            properties:
              host:
                description: The host address of the application
                type: string
            type: object
        type: object
    served: true