apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    type: frontend
  name: app-frontend
spec:
  compositeTypeRef:
    apiVersion: kaonix.com/v1alpha1
    kind: App
  mode: Pipeline
  pipeline:
  - functionRef:
      name: kaonix-platformfunction-app
    step: function-app
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: automatically-detect-ready-composed-resources
