FROM alpine:latest 

ARG KIND_VERSION=0.14.0

RUN apk add --no-cache curl docker-cli git && \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl && \
    curl -L https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64 -o /usr/local/bin/kind && \
    chmod +x /usr/local/bin/kind && \
    curl -sL "https://raw.githubusercontent.com/crossplane/crossplane/main/install.sh" | sh &&  mv crossplane /usr/local/bin && \
    rm -rf /var/cache/apk/*
