// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ReleaseAPIVersion.
const (
	ReleaseAPIVersionHelmCrossplaneIoV1Beta1 ReleaseAPIVersion = "helm.crossplane.io/v1beta1"
)

// Valid indicates whether the value is a known member of the ReleaseAPIVersion enum.
func (e ReleaseAPIVersion) Valid() bool {
	switch e {
	case ReleaseAPIVersionHelmCrossplaneIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseKind.
const (
	ReleaseKindRelease ReleaseKind = "Release"
)

// Valid indicates whether the value is a known member of the ReleaseKind enum.
func (e ReleaseKind) Valid() bool {
	switch e {
	case ReleaseKindRelease:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseSpecDeletionPolicy.
const (
	ReleaseSpecDeletionPolicyDelete ReleaseSpecDeletionPolicy = "Delete"
	ReleaseSpecDeletionPolicyOrphan ReleaseSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the ReleaseSpecDeletionPolicy enum.
func (e ReleaseSpecDeletionPolicy) Valid() bool {
	switch e {
	case ReleaseSpecDeletionPolicyDelete:
		return true
	case ReleaseSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseSpecManagementPoliciesItem.
const (
	ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItem               ReleaseSpecManagementPoliciesItem = "*"
	ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemCreate         ReleaseSpecManagementPoliciesItem = "Create"
	ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemDelete         ReleaseSpecManagementPoliciesItem = "Delete"
	ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemLateInitialize ReleaseSpecManagementPoliciesItem = "LateInitialize"
	ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemObserve        ReleaseSpecManagementPoliciesItem = "Observe"
	ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemUpdate         ReleaseSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the ReleaseSpecManagementPoliciesItem enum.
func (e ReleaseSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItem:
		return true
	case ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemCreate:
		return true
	case ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemDelete:
		return true
	case ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemLateInitialize:
		return true
	case ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemObserve:
		return true
	case ReleaseSpecManagementPoliciesItemReleaseSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseSpecProviderConfigRefPolicyResolution.
const (
	ReleaseSpecProviderConfigRefPolicyResolutionOptional ReleaseSpecProviderConfigRefPolicyResolution = "Optional"
	ReleaseSpecProviderConfigRefPolicyResolutionRequired ReleaseSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the ReleaseSpecProviderConfigRefPolicyResolution enum.
func (e ReleaseSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case ReleaseSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case ReleaseSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for ReleaseSpecProviderConfigRefPolicyResolve.
const (
	ReleaseSpecProviderConfigRefPolicyResolveAlways       ReleaseSpecProviderConfigRefPolicyResolve = "Always"
	ReleaseSpecProviderConfigRefPolicyResolveIfNotPresent ReleaseSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the ReleaseSpecProviderConfigRefPolicyResolve enum.
func (e ReleaseSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case ReleaseSpecProviderConfigRefPolicyResolveAlways:
		return true
	case ReleaseSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoCrossplaneHelmV1Beta1Release A Release is an example API type
type IoCrossplaneHelmV1Beta1Release = Release

// ReleaseAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ReleaseAPIVersion string

// ReleaseKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ReleaseKind string

// ReleaseSpecConnectionDetailsItem ConnectionDetail todo
type ReleaseSpecConnectionDetailsItem struct {
	// APIVersion API version of the referent.
	APIVersion *string `json:"apiVersion,omitempty"`

	// FieldPath If referring to a piece of an object instead of an entire object, this string
	// should contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].
	// For example, if the object reference is to a container within a pod, this would take on a value like:
	// "spec.containers{name}" (where "name" refers to the name of the container that triggered
	// the event) or if no container name is specified "spec.containers[2]" (container with
	// index 2 in this pod). This syntax is chosen only to have some well-defined way of
	// referencing a part of an object.
	FieldPath *string `json:"fieldPath,omitempty"`

	// Kind Kind of the referent.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
	Namespace *string `json:"namespace,omitempty"`

	// ResourceVersion Specific resourceVersion to which this reference is made, if any.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
	ResourceVersion *string `json:"resourceVersion,omitempty"`

	// SkipPartOfReleaseCheck SkipPartOfReleaseCheck skips check for meta.helm.sh/release-name annotation.
	SkipPartOfReleaseCheck *bool   `json:"skipPartOfReleaseCheck,omitempty"`
	ToConnectionSecretKey  *string `json:"toConnectionSecretKey,omitempty"`

	// UID UID of the referent.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
	UID *string `json:"uid,omitempty"`
}

// ReleaseSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type ReleaseSpecDeletionPolicy string

// ReleaseSpecForProviderChartPullSecretRef PullSecretRef is reference to the secret containing credentials to helm repository.
// The secret must contain 'username' and 'password' keys. Optional - if not provided,
// the default credential chain is used (AWS IRSA, Azure/GCP Workload Identity, etc.).
type ReleaseSpecForProviderChartPullSecretRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ReleaseSpecForProviderChart A ChartSpec defines the chart spec for a Release
type ReleaseSpecForProviderChart struct {
	// Digest Digest is the OCI image digest in the format "sha256:abc123..."
	// Only supported for OCI registries. When specified, the chart will be pulled by digest.
	// Can be used alone or in combination with Version. Optional.
	Digest *string `json:"digest,omitempty"`

	// Name Name of Helm chart, required if ChartSpec.URL not set
	Name *string `json:"name,omitempty"`

	// PullSecretRef PullSecretRef is reference to the secret containing credentials to helm repository.
	// The secret must contain 'username' and 'password' keys. Optional - if not provided,
	// the default credential chain is used (AWS IRSA, Azure/GCP Workload Identity, etc.).
	PullSecretRef *ReleaseSpecForProviderChartPullSecretRef `json:"pullSecretRef,omitempty"`

	// Repository Repository: Helm repository URL, required if ChartSpec.URL not set
	Repository *string `json:"repository,omitempty"`

	// URL URL to chart package (typically .tgz), optional and overrides others fields in the spec
	URL *string `json:"url,omitempty"`

	// Version Version of Helm chart. Optional when Digest is specified.
	// If not set and Digest is not specified, gets late initialized with the latest available version.
	// If not set and Digest is specified, version is NOT late initialized to avoid spec drift.
	// The actual deployed version is always available in status.atProvider.version for observability.
	Version *string `json:"version,omitempty"`
}

// ReleaseSpecForProviderPatchesFromItemConfigMapKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
type ReleaseSpecForProviderPatchesFromItemConfigMapKeyRef struct {
	Key       *string `json:"key,omitempty"`
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Optional  *bool   `json:"optional,omitempty"`
}

// ReleaseSpecForProviderPatchesFromItemSecretKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
type ReleaseSpecForProviderPatchesFromItemSecretKeyRef struct {
	Key       *string `json:"key,omitempty"`
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Optional  *bool   `json:"optional,omitempty"`
}

// ReleaseSpecForProviderPatchesFromItem ValueFromSource represents source of a value
type ReleaseSpecForProviderPatchesFromItem struct {
	// ConfigMapKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
	ConfigMapKeyRef *ReleaseSpecForProviderPatchesFromItemConfigMapKeyRef `json:"configMapKeyRef,omitempty"`

	// SecretKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
	SecretKeyRef *ReleaseSpecForProviderPatchesFromItemSecretKeyRef `json:"secretKeyRef,omitempty"`
}

// ReleaseSpecForProviderSetItemValueFromConfigMapKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
type ReleaseSpecForProviderSetItemValueFromConfigMapKeyRef struct {
	Key       *string `json:"key,omitempty"`
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Optional  *bool   `json:"optional,omitempty"`
}

// ReleaseSpecForProviderSetItemValueFromSecretKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
type ReleaseSpecForProviderSetItemValueFromSecretKeyRef struct {
	Key       *string `json:"key,omitempty"`
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Optional  *bool   `json:"optional,omitempty"`
}

// ReleaseSpecForProviderSetItemValueFrom ValueFromSource represents source of a value
type ReleaseSpecForProviderSetItemValueFrom struct {
	// ConfigMapKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
	ConfigMapKeyRef *ReleaseSpecForProviderSetItemValueFromConfigMapKeyRef `json:"configMapKeyRef,omitempty"`

	// SecretKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
	SecretKeyRef *ReleaseSpecForProviderSetItemValueFromSecretKeyRef `json:"secretKeyRef,omitempty"`
}

// ReleaseSpecForProviderSetItem SetVal represents a "set" value override in a Release
type ReleaseSpecForProviderSetItem struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`

	// ValueFrom ValueFromSource represents source of a value
	ValueFrom *ReleaseSpecForProviderSetItemValueFrom `json:"valueFrom,omitempty"`
}

// ReleaseSpecForProviderValues defines model for .
type ReleaseSpecForProviderValues = map[string]interface{}

// ReleaseSpecForProviderValuesFromItemConfigMapKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
type ReleaseSpecForProviderValuesFromItemConfigMapKeyRef struct {
	Key       *string `json:"key,omitempty"`
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Optional  *bool   `json:"optional,omitempty"`
}

// ReleaseSpecForProviderValuesFromItemSecretKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
type ReleaseSpecForProviderValuesFromItemSecretKeyRef struct {
	Key       *string `json:"key,omitempty"`
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	Optional  *bool   `json:"optional,omitempty"`
}

// ReleaseSpecForProviderValuesFromItem ValueFromSource represents source of a value
type ReleaseSpecForProviderValuesFromItem struct {
	// ConfigMapKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
	ConfigMapKeyRef *ReleaseSpecForProviderValuesFromItemConfigMapKeyRef `json:"configMapKeyRef,omitempty"`

	// SecretKeyRef DataKeySelector defines required spec to access a key of a configmap or secret
	SecretKeyRef *ReleaseSpecForProviderValuesFromItemSecretKeyRef `json:"secretKeyRef,omitempty"`
}

// ReleaseSpecForProvider ReleaseParameters are the configurable fields of a Release.
type ReleaseSpecForProvider struct {
	// Chart A ChartSpec defines the chart spec for a Release
	Chart *ReleaseSpecForProviderChart `json:"chart,omitempty"`

	// InsecureSkipTLSVerify InsecureSkipTLSVerify skips tls certificate checks for the chart download
	InsecureSkipTLSVerify *bool `json:"insecureSkipTLSVerify,omitempty"`

	// MaxHistory MaxHistory limits the maximum number of revisions saved per release. Use 0 for no limit.
	MaxHistory *int `json:"maxHistory,omitempty"`

	// Namespace Namespace to install the release into.
	Namespace *string `json:"namespace,omitempty"`

	// PatchesFrom PatchesFrom describe patches to be applied to the rendered manifests.
	PatchesFrom *[]ReleaseSpecForProviderPatchesFromItem `json:"patchesFrom,omitempty"`

	// PlainHTTP PlainHTTP uses insecure HTTP connections for the chart download
	PlainHTTP *bool                            `json:"plainHTTP,omitempty"`
	Set       *[]ReleaseSpecForProviderSetItem `json:"set,omitempty"`

	// SkipCRDs SkipCRDs skips installation of CRDs for the release.
	SkipCRDs *bool `json:"skipCRDs,omitempty"`

	// SkipCreateNamespace SkipCreateNamespace won't create the namespace for the release. This requires the namespace to already exist.
	SkipCreateNamespace *bool `json:"skipCreateNamespace,omitempty"`

	// SsaForceConflicts SSAForceConflicts forces Kubernetes server-side apply to overwrite
	// field conflicts ("become sole manager") when installing, upgrading,
	// or rolling back the release.
	// See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
	SsaForceConflicts *bool `json:"ssaForceConflicts,omitempty"`

	// TakeOwnership TakeOwnership ignores Helm ownership validation and adopts pre-existing releases.
	// This is a ONE-TIME operation: after the first successful deployment, the flag is recorded
	// in status.atProvider.ownershipTaken and subsequent reconciles use normal Helm validation.
	// This prevents silent adoption of unrelated resources during chart upgrades.
	// Use this field to migrate manually-deployed Helm releases into Crossplane management.
	TakeOwnership *bool                                   `json:"takeOwnership,omitempty"`
	Values        *ReleaseSpecForProviderValues           `json:"values,omitempty"`
	ValuesFrom    *[]ReleaseSpecForProviderValuesFromItem `json:"valuesFrom,omitempty"`

	// Wait Wait for the release to become ready.
	Wait *bool `json:"wait,omitempty"`

	// WaitTimeout WaitTimeout is the duration Helm will wait for the release to become
	// ready. Only applies if wait is also set. Defaults to 5m.
	WaitTimeout *string `json:"waitTimeout,omitempty"`
}

// ReleaseSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type ReleaseSpecManagementPoliciesItem string

// ReleaseSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type ReleaseSpecProviderConfigRefPolicyResolution string

// ReleaseSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type ReleaseSpecProviderConfigRefPolicyResolve string

// ReleaseSpecProviderConfigRefPolicy Policies for referencing.
type ReleaseSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *ReleaseSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *ReleaseSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// ReleaseSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type ReleaseSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *ReleaseSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// ReleaseSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type ReleaseSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ReleaseSpec A ReleaseSpec defines the desired state of a Release.
type ReleaseSpec struct {
	ConnectionDetails *[]ReleaseSpecConnectionDetailsItem `json:"connectionDetails,omitempty"`

	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *ReleaseSpecDeletionPolicy `json:"deletionPolicy,omitempty"`

	// ForProvider ReleaseParameters are the configurable fields of a Release.
	ForProvider *ReleaseSpecForProvider `json:"forProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]ReleaseSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *ReleaseSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// RollbackLimit RollbackRetriesLimit is max number of attempts to retry Helm deployment by rolling back the release.
	RollbackLimit *int32 `json:"rollbackLimit,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *ReleaseSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// ReleaseStatusAtProvider ReleaseObservation are the observable fields of a Release.
type ReleaseStatusAtProvider struct {
	// Digest Digest is the last successfully deployed chart digest (for OCI charts only).
	Digest *string `json:"digest,omitempty"`

	// OwnershipTaken OwnershipTaken indicates that spec.forProvider.takeOwnership was used for initial adoption.
	// Once set to true, subsequent reconciles use normal Helm validation instead of takeOwnership,
	// preventing silent adoption of unrelated resources during upgrades.
	OwnershipTaken     *bool   `json:"ownershipTaken,omitempty"`
	ReleaseDescription *string `json:"releaseDescription,omitempty"`
	Revision           *int    `json:"revision,omitempty"`

	// State Status is the status of a release
	State *string `json:"state,omitempty"`

	// Version Version is the actual deployed chart version.
	Version *string `json:"version,omitempty"`
}

// ReleaseStatusConditionsItem A Condition that may apply to a resource.
type ReleaseStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ReleaseStatus A ReleaseStatus represents the observed state of a Release.
type ReleaseStatus struct {
	// AtProvider ReleaseObservation are the observable fields of a Release.
	AtProvider *ReleaseStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]ReleaseStatusConditionsItem `json:"conditions,omitempty"`
	Failed     *int32                         `json:"failed,omitempty"`

	// LastHandledReconcileAt LastHandledReconcileAt holds the value of the most recent
	// reconcile-requested-at annotation token that the controller has
	// processed. Users can compare this to the annotation to determine
	// whether a reconcile request has been handled.
	LastHandledReconcileAt *string `json:"lastHandledReconcileAt,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64  `json:"observedGeneration,omitempty"`
	PatchesSha         *string `json:"patchesSha,omitempty"`
	Synced             *bool   `json:"synced,omitempty"`
}

// Release A Release is an example API type
type Release struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ReleaseAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ReleaseKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec A ReleaseSpec defines the desired state of a Release.
	Spec *ReleaseSpec `json:"spec,omitempty"`

	// Status A ReleaseStatus represents the observed state of a Release.
	Status *ReleaseStatus `json:"status,omitempty"`
}

// IoCrossplaneHelmV1Beta1ReleaseList ReleaseList is a list of Release
type IoCrossplaneHelmV1Beta1ReleaseList = ReleaseList

// ReleaseList ReleaseList is a list of Release
type ReleaseList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of releases. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneHelmV1Beta1Release `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
