// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for InputAPIVersion.
const (
	InputAPIVersionAutoreadyFnCrossplaneIoV1Beta1 InputAPIVersion = "autoready.fn.crossplane.io/v1beta1"
)

// Valid indicates whether the value is a known member of the InputAPIVersion enum.
func (e InputAPIVersion) Valid() bool {
	switch e {
	case InputAPIVersionAutoreadyFnCrossplaneIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for InputKind.
const (
	InputKindInput InputKind = "Input"
)

// Valid indicates whether the value is a known member of the InputKind enum.
func (e InputKind) Valid() bool {
	switch e {
	case InputKindInput:
		return true
	default:
		return false
	}
}

// IoCrossplaneFnAutoreadyV1Beta1Input Input is used to provide inputs to this Function.
type IoCrossplaneFnAutoreadyV1Beta1Input = Input

// InputAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type InputAPIVersion string

// InputKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type InputKind string

// Input Input is used to provide inputs to this Function.
type Input struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *InputAPIVersion `json:"apiVersion,omitempty"`

	// CelHealthCheckCustomization CELHealthCheckCustomization is a inline map of CEL health check customizations
	// Inline customizations are merged with from Context customizations
	// and take precedence over Context-provided healthchecks allowing for granular overwrites
	CelHealthCheckCustomization *map[string]string `json:"celHealthCheckCustomization,omitempty"`

	// CelHealthCheckCustomizationFrom CELHealthCheckCustomizationFrom is a reference to fetch CEL health check customizations from context
	CelHealthCheckCustomizationFrom *string `json:"celHealthCheckCustomizationFrom,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *InputKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// TTL TTL for which a response can be cached in time.Duration format
	TTL *string `json:"ttl,omitempty"`
}

// IoCrossplaneFnAutoreadyV1Beta1InputList InputList is a list of Input
type IoCrossplaneFnAutoreadyV1Beta1InputList = InputList

// InputList InputList is a list of Input
type InputList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of inputs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneFnAutoreadyV1Beta1Input `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
