apiVersion: kaonix.com/v1alpha1
kind: App
metadata:
  name: devops-toolkit
  namespace: platform
  labels:
    app-owner: vfarcic
spec:
  id: devops-toolkit
  crossplane:
    compositionSelector:
      matchLabels:
        type: frontend
  parameters:
    namespace: platform
    image: vfarcic/devops-toolkit-series:4.0.0
    port: 80
