apiVersion: kaonix.com/v1alpha1
kind: App
metadata:
  name: devops-toolkit
  namespace: a-team
  labels:
    app-owner: vfarcic
spec:
  id: devops-toolkit
  crossplane:
    compositionSelector:
      matchLabels:
        type: frontend
  parameters:
    namespace: a-team
    image: vfarcic/devops-toolkit-series:4.0.0
    host: devops-toolkit.127.0.0.1.nip.io
