# generated by datamodel-codegen:
#   filename:  workdir/gotemplating_fn_crossplane_io_v1beta1_gotemplate.yaml

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

from .....k8s.apimachinery.pkg.apis.meta import v1


class Delims(BaseModel):
    left: str | None = '{{'
    """
    Template start characters
    """
    right: str | None = '}}'
    """
    Template end characters
    """


class Environment(BaseModel):
    key: str | None = None


class FileSystem(BaseModel):
    dirPath: str | None = None


class Inline(BaseModel):
    template: str | None = None
    templates: list[str] | None = None


class GoTemplate(BaseModel):
    apiVersion: Literal['gotemplating.fn.crossplane.io/v1beta1'] | None = (
        'gotemplating.fn.crossplane.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    delims: Delims | None = None
    """
    Template delimiters
    """
    environment: Environment | None = None
    """
    Environment is the key that defines the location of the templates in the environment
    """
    fileSystem: FileSystem | None = None
    """
    FileSystem is the folder path where the templates are located
    """
    inline: Inline | None = None
    """
    Inline is the inline form input of the templates
    """
    kind: Literal['GoTemplate'] | None = 'GoTemplate'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    options: list[str] | None = None
    """
    Options to set for the template engine. Valid options are documented at https://pkg.go.dev/text/template#Template.Option
    """
    source: str
    """
    Source specifies the different types of input sources that can be used with this function
    """


class GoTemplateList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[GoTemplate]
    """
    List of gotemplates. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """