# generated by datamodel-codegen:
#   filename:  workdir/kaonix_com_v1alpha1_database.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = 'Automatic'
    resourceRefs: list[ResourceRef] | None = None


class Parameters(BaseModel):
    database: str | None = 'app'
    """
    The name of the database to create.
    """
    instances: int | None = 1
    """
    Number of PostgreSQL instances (replicas).
    """
    namespace: str
    """
    The namespace for the database resources.
    """
    size: str | None = 'small'
    """
    Predefined size preset. Supported values are `small`, `medium`, and `large`.

    """
    storageSize: str | None = None
    """
    Explicit PVC storage size (e.g., 1Gi). Overrides the size preset when set.

    """
    version: str | None = '16'
    """
    PostgreSQL major version (e.g., 13, 14, 15, 16).
    """


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    id: str
    """
    Unique identifier for this database.
    """
    parameters: Parameters


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    dbName: str | None = None
    """
    Name of the database.
    """
    host: str | None = None
    """
    Internal Kubernetes Service address.
    """
    port: int | None = None
    """
    PostgreSQL port.
    """
    secretName: str | None = None
    """
    Name of the Secret containing credentials.
    """


class Database(BaseModel):
    apiVersion: Literal['kaonix.com/v1alpha1'] | None = 'kaonix.com/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Database'] | None = 'Database'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Status | None = None


class DatabaseList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Database]
    """
    List of databases. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """