# generated by datamodel-codegen:
#   filename:  workdir/kaonix_com_v1alpha1_network.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = 'Automatic'
    resourceRefs: list[ResourceRef] | None = None


class Ingress(BaseModel):
    host: str | None = None
    """
    The hostname for the Ingress rule.
    """
    path: str | None = '/'
    """
    The path for the Ingress rule.
    """
    tlsSecret: str | None = None
    """
    TLS secret name for HTTPS. If empty, no TLS.
    """


class NetworkPolicy(BaseModel):
    egress: list[str] | None = None
    """
    Allowed egress destinations as CIDR blocks.
    """
    ingress: list[str] | None = None
    """
    Allowed ingress sources as CIDR blocks.
    """


class Port(BaseModel):
    port: int
    """
    The port to expose.
    """
    protocol: str | None = 'TCP'
    """
    The protocol (TCP or UDP).
    """
    targetPort: int | None = None
    """
    The port on the target pod. Defaults to port.
    """


class Parameters(BaseModel):
    appName: str
    """
    The name of the target application (used for selector matching).
    """
    dns: str | None = None
    """
    External DNS name (creates an ExternalName service).
    """
    ingress: Ingress | None = None
    """
    Ingress configuration (optional).
    """
    namespace: str | None = 'default'
    """
    The namespace of the target application.
    """
    networkPolicy: NetworkPolicy | None = None
    """
    NetworkPolicy configuration (optional).
    """
    ports: list[Port]
    """
    List of port mappings to expose.
    """


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    id: str
    """
    Unique identifier for this network configuration.
    """
    parameters: Parameters


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    ingressHost: str | None = None
    """
    The Ingress host.
    """
    networkPolicyName: str | None = None
    """
    The name of the created NetworkPolicy.
    """
    serviceName: str | None = None
    """
    The name of the created Service.
    """


class Network(BaseModel):
    apiVersion: Literal['kaonix.com/v1alpha1'] | None = 'kaonix.com/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Network'] | None = 'Network'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    status: Status | None = None


class NetworkList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Network]
    """
    List of networks. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """