// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ProviderConfigUsageAPIVersion.
const (
	ProviderConfigUsageAPIVersionHelmCrossplaneIoV1Alpha1 ProviderConfigUsageAPIVersion = "helm.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ProviderConfigUsageAPIVersion enum.
func (e ProviderConfigUsageAPIVersion) Valid() bool {
	switch e {
	case ProviderConfigUsageAPIVersionHelmCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigUsageKind.
const (
	ProviderConfigUsageKindProviderConfigUsage ProviderConfigUsageKind = "ProviderConfigUsage"
)

// Valid indicates whether the value is a known member of the ProviderConfigUsageKind enum.
func (e ProviderConfigUsageKind) Valid() bool {
	switch e {
	case ProviderConfigUsageKindProviderConfigUsage:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigUsageProviderConfigRefPolicyResolution.
const (
	ProviderConfigUsageProviderConfigRefPolicyResolutionOptional ProviderConfigUsageProviderConfigRefPolicyResolution = "Optional"
	ProviderConfigUsageProviderConfigRefPolicyResolutionRequired ProviderConfigUsageProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the ProviderConfigUsageProviderConfigRefPolicyResolution enum.
func (e ProviderConfigUsageProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case ProviderConfigUsageProviderConfigRefPolicyResolutionOptional:
		return true
	case ProviderConfigUsageProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigUsageProviderConfigRefPolicyResolve.
const (
	ProviderConfigUsageProviderConfigRefPolicyResolveAlways       ProviderConfigUsageProviderConfigRefPolicyResolve = "Always"
	ProviderConfigUsageProviderConfigRefPolicyResolveIfNotPresent ProviderConfigUsageProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the ProviderConfigUsageProviderConfigRefPolicyResolve enum.
func (e ProviderConfigUsageProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case ProviderConfigUsageProviderConfigRefPolicyResolveAlways:
		return true
	case ProviderConfigUsageProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoCrossplaneHelmV1Alpha1ProviderConfigUsage A ProviderConfigUsage indicates that a resource is using a ProviderConfig.
type IoCrossplaneHelmV1Alpha1ProviderConfigUsage = ProviderConfigUsage

// ProviderConfigUsageAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ProviderConfigUsageAPIVersion string

// ProviderConfigUsageKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ProviderConfigUsageKind string

// ProviderConfigUsageProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type ProviderConfigUsageProviderConfigRefPolicyResolution string

// ProviderConfigUsageProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type ProviderConfigUsageProviderConfigRefPolicyResolve string

// ProviderConfigUsageProviderConfigRefPolicy Policies for referencing.
type ProviderConfigUsageProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *ProviderConfigUsageProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *ProviderConfigUsageProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// ProviderConfigUsageProviderConfigRef ProviderConfigReference to the provider config being used.
type ProviderConfigUsageProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *ProviderConfigUsageProviderConfigRefPolicy `json:"policy,omitempty"`
}

// ProviderConfigUsageResourceRef ResourceReference to the managed resource using the provider config.
type ProviderConfigUsageResourceRef struct {
	// APIVersion APIVersion of the referenced object.
	APIVersion *string `json:"apiVersion,omitempty"`

	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// UID UID of the referenced object.
	UID *string `json:"uid,omitempty"`
}

// ProviderConfigUsage A ProviderConfigUsage indicates that a resource is using a ProviderConfig.
type ProviderConfigUsage struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ProviderConfigUsageAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ProviderConfigUsageKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// ProviderConfigRef ProviderConfigReference to the provider config being used.
	ProviderConfigRef *ProviderConfigUsageProviderConfigRef `json:"providerConfigRef,omitempty"`

	// ResourceRef ResourceReference to the managed resource using the provider config.
	ResourceRef *ProviderConfigUsageResourceRef `json:"resourceRef,omitempty"`
}

// IoCrossplaneHelmV1Alpha1ProviderConfigUsageList ProviderConfigUsageList is a list of ProviderConfigUsage
type IoCrossplaneHelmV1Alpha1ProviderConfigUsageList = ProviderConfigUsageList

// ProviderConfigUsageList ProviderConfigUsageList is a list of ProviderConfigUsage
type ProviderConfigUsageList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of providerconfigusages. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneHelmV1Alpha1ProviderConfigUsage `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
