// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version (devel) DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for ProviderConfigAPIVersion.
const (
	ProviderConfigAPIVersionHelmCrossplaneIoV1Alpha1 ProviderConfigAPIVersion = "helm.crossplane.io/v1alpha1"
)

// Valid indicates whether the value is a known member of the ProviderConfigAPIVersion enum.
func (e ProviderConfigAPIVersion) Valid() bool {
	switch e {
	case ProviderConfigAPIVersionHelmCrossplaneIoV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigKind.
const (
	ProviderConfigKindProviderConfig ProviderConfigKind = "ProviderConfig"
)

// Valid indicates whether the value is a known member of the ProviderConfigKind enum.
func (e ProviderConfigKind) Valid() bool {
	switch e {
	case ProviderConfigKindProviderConfig:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigSpecCredentialsSource.
const (
	ProviderConfigSpecCredentialsSourceEnvironment      ProviderConfigSpecCredentialsSource = "Environment"
	ProviderConfigSpecCredentialsSourceFilesystem       ProviderConfigSpecCredentialsSource = "Filesystem"
	ProviderConfigSpecCredentialsSourceInjectedIdentity ProviderConfigSpecCredentialsSource = "InjectedIdentity"
	ProviderConfigSpecCredentialsSourceNone             ProviderConfigSpecCredentialsSource = "None"
	ProviderConfigSpecCredentialsSourceSecret           ProviderConfigSpecCredentialsSource = "Secret"
)

// Valid indicates whether the value is a known member of the ProviderConfigSpecCredentialsSource enum.
func (e ProviderConfigSpecCredentialsSource) Valid() bool {
	switch e {
	case ProviderConfigSpecCredentialsSourceEnvironment:
		return true
	case ProviderConfigSpecCredentialsSourceFilesystem:
		return true
	case ProviderConfigSpecCredentialsSourceInjectedIdentity:
		return true
	case ProviderConfigSpecCredentialsSourceNone:
		return true
	case ProviderConfigSpecCredentialsSourceSecret:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigSpecIdentitySource.
const (
	ProviderConfigSpecIdentitySourceEnvironment      ProviderConfigSpecIdentitySource = "Environment"
	ProviderConfigSpecIdentitySourceFilesystem       ProviderConfigSpecIdentitySource = "Filesystem"
	ProviderConfigSpecIdentitySourceInjectedIdentity ProviderConfigSpecIdentitySource = "InjectedIdentity"
	ProviderConfigSpecIdentitySourceNone             ProviderConfigSpecIdentitySource = "None"
	ProviderConfigSpecIdentitySourceSecret           ProviderConfigSpecIdentitySource = "Secret"
)

// Valid indicates whether the value is a known member of the ProviderConfigSpecIdentitySource enum.
func (e ProviderConfigSpecIdentitySource) Valid() bool {
	switch e {
	case ProviderConfigSpecIdentitySourceEnvironment:
		return true
	case ProviderConfigSpecIdentitySourceFilesystem:
		return true
	case ProviderConfigSpecIdentitySourceInjectedIdentity:
		return true
	case ProviderConfigSpecIdentitySourceNone:
		return true
	case ProviderConfigSpecIdentitySourceSecret:
		return true
	default:
		return false
	}
}

// Defines values for ProviderConfigSpecIdentityType.
const (
	ProviderConfigSpecIdentityTypeGoogleApplicationCredentials ProviderConfigSpecIdentityType = "GoogleApplicationCredentials"
)

// Valid indicates whether the value is a known member of the ProviderConfigSpecIdentityType enum.
func (e ProviderConfigSpecIdentityType) Valid() bool {
	switch e {
	case ProviderConfigSpecIdentityTypeGoogleApplicationCredentials:
		return true
	default:
		return false
	}
}

// IoCrossplaneHelmV1Alpha1ProviderConfig A ProviderConfig configures a Helm 'provider', i.e. a connection to a particular
type IoCrossplaneHelmV1Alpha1ProviderConfig = ProviderConfig

// ProviderConfigAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type ProviderConfigAPIVersion string

// ProviderConfigKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type ProviderConfigKind string

// ProviderConfigSpecCredentialsEnv Env is a reference to an environment variable that contains credentials
// that must be used to connect to the provider.
type ProviderConfigSpecCredentialsEnv struct {
	// Name Name is the name of an environment variable.
	Name *string `json:"name,omitempty"`
}

// ProviderConfigSpecCredentialsFs Fs is a reference to a filesystem location that contains credentials that
// must be used to connect to the provider.
type ProviderConfigSpecCredentialsFs struct {
	// Path Path is a filesystem path.
	Path *string `json:"path,omitempty"`
}

// ProviderConfigSpecCredentialsSecretRef A SecretRef is a reference to a secret key that contains the credentials
// that must be used to connect to the provider.
type ProviderConfigSpecCredentialsSecretRef struct {
	// Key The key to select.
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ProviderConfigSpecCredentialsSource Source of the provider credentials.
type ProviderConfigSpecCredentialsSource string

// ProviderConfigSpecCredentials Credentials used to connect to the Kubernetes API. Typically a
// kubeconfig file. Use InjectedIdentity for in-cluster config.
type ProviderConfigSpecCredentials struct {
	// Env Env is a reference to an environment variable that contains credentials
	// that must be used to connect to the provider.
	Env *ProviderConfigSpecCredentialsEnv `json:"env,omitempty"`

	// Fs Fs is a reference to a filesystem location that contains credentials that
	// must be used to connect to the provider.
	Fs *ProviderConfigSpecCredentialsFs `json:"fs,omitempty"`

	// SecretRef A SecretRef is a reference to a secret key that contains the credentials
	// that must be used to connect to the provider.
	SecretRef *ProviderConfigSpecCredentialsSecretRef `json:"secretRef,omitempty"`

	// Source Source of the provider credentials.
	Source *ProviderConfigSpecCredentialsSource `json:"source,omitempty"`
}

// ProviderConfigSpecIdentityEnv Env is a reference to an environment variable that contains credentials
// that must be used to connect to the provider.
type ProviderConfigSpecIdentityEnv struct {
	// Name Name is the name of an environment variable.
	Name *string `json:"name,omitempty"`
}

// ProviderConfigSpecIdentityFs Fs is a reference to a filesystem location that contains credentials that
// must be used to connect to the provider.
type ProviderConfigSpecIdentityFs struct {
	// Path Path is a filesystem path.
	Path *string `json:"path,omitempty"`
}

// ProviderConfigSpecIdentitySecretRef A SecretRef is a reference to a secret key that contains the credentials
// that must be used to connect to the provider.
type ProviderConfigSpecIdentitySecretRef struct {
	// Key The key to select.
	Key *string `json:"key,omitempty"`

	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// ProviderConfigSpecIdentitySource Source of the provider credentials.
type ProviderConfigSpecIdentitySource string

// ProviderConfigSpecIdentityType Type of identity.
type ProviderConfigSpecIdentityType string

// ProviderConfigSpecIdentity Identity used to authenticate to the Kubernetes API. The identity
// credentials can be used to supplement kubeconfig 'credentials', for
// example by configuring a bearer token source such as OAuth.
type ProviderConfigSpecIdentity struct {
	// Env Env is a reference to an environment variable that contains credentials
	// that must be used to connect to the provider.
	Env *ProviderConfigSpecIdentityEnv `json:"env,omitempty"`

	// Fs Fs is a reference to a filesystem location that contains credentials that
	// must be used to connect to the provider.
	Fs *ProviderConfigSpecIdentityFs `json:"fs,omitempty"`

	// SecretRef A SecretRef is a reference to a secret key that contains the credentials
	// that must be used to connect to the provider.
	SecretRef *ProviderConfigSpecIdentitySecretRef `json:"secretRef,omitempty"`

	// Source Source of the provider credentials.
	Source *ProviderConfigSpecIdentitySource `json:"source,omitempty"`

	// Type Type of identity.
	Type *ProviderConfigSpecIdentityType `json:"type,omitempty"`
}

// ProviderConfigSpec A ProviderConfigSpec defines the desired state of a Provider.
type ProviderConfigSpec struct {
	// Credentials Credentials used to connect to the Kubernetes API. Typically a
	// kubeconfig file. Use InjectedIdentity for in-cluster config.
	Credentials *ProviderConfigSpecCredentials `json:"credentials,omitempty"`

	// Identity Identity used to authenticate to the Kubernetes API. The identity
	// credentials can be used to supplement kubeconfig 'credentials', for
	// example by configuring a bearer token source such as OAuth.
	Identity *ProviderConfigSpecIdentity `json:"identity,omitempty"`
}

// ProviderConfigStatusConditionsItem A Condition that may apply to a resource.
type ProviderConfigStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// ProviderConfigStatus A ProviderConfigStatus defines the status of a Provider.
type ProviderConfigStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]ProviderConfigStatusConditionsItem `json:"conditions,omitempty"`

	// Users Users of this provider configuration.
	Users *int64 `json:"users,omitempty"`
}

// ProviderConfig A ProviderConfig configures a Helm 'provider', i.e. a connection to a particular
type ProviderConfig struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *ProviderConfigAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *ProviderConfigKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec A ProviderConfigSpec defines the desired state of a Provider.
	Spec *ProviderConfigSpec `json:"spec,omitempty"`

	// Status A ProviderConfigStatus defines the status of a Provider.
	Status *ProviderConfigStatus `json:"status,omitempty"`
}

// IoCrossplaneHelmV1Alpha1ProviderConfigList ProviderConfigList is a list of ProviderConfig
type IoCrossplaneHelmV1Alpha1ProviderConfigList = ProviderConfigList

// ProviderConfigList ProviderConfigList is a list of ProviderConfig
type ProviderConfigList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of providerconfigs. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoCrossplaneHelmV1Alpha1ProviderConfig `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
