apiVersion: ops.crossplane.io/v1alpha1
kind: Operation
metadata:
  name: operation-madmax1-recovery-python
spec:
  mode: Pipeline
  pipeline:
  - step: prepare-cluster
    functionRef:
      name: function-recovery-python
    requirements:
      requiredResources:
      - requirementName: postgresql
        apiVersion: database.kaonix.inc.fr/v1alpha1
        kind: PostgreSQL
        name: madmax1
        namespace: platform
    input:
      apiVersion: function-recovery-python.fn.kaonix.com/v1beta1
      kind: Input
      spec:
        mode: prepare
        target:
          namespace: platform
        planName: madmax1-recovery-plan
  - step: delete-cluster
    functionRef:
      name: function-recovery-python
    requirements:
      requiredResources:
      - requirementName: postgresql
        apiVersion: database.kaonix.inc.fr/v1alpha1
        kind: PostgreSQL
        name: madmax1
        namespace: platform
    input:
      apiVersion: function-recovery-python.fn.kaonix.com/v1beta1
      kind: Input
      spec:
        mode: delete
        target:
          namespace: platform
  - step: restore-cluster
    functionRef:
      name: function-recovery-python
    requirements:
      requiredResources:
      - requirementName: postgresql
        apiVersion: database.kaonix.inc.fr/v1alpha1
        kind: PostgreSQL
        name: madmax1
        namespace: platform
      - requirementName: recovery-plan
        apiVersion: v1
        kind: ConfigMap
        name: madmax1-recovery-plan
        namespace: platform
    input:
      apiVersion: function-recovery-python.fn.kaonix.com/v1beta1
      kind: Input
      spec:
        mode: restore
        target:
          namespace: platform
        planName: madmax1-recovery-plan
        backup:
          name: madmax1-backup
          namespace: platform
  - step: cleanup-recovery-bootstrap
    functionRef:
      name: function-recovery-python
    requirements:
      requiredResources:
      - requirementName: postgresql
        apiVersion: database.kaonix.inc.fr/v1alpha1
        kind: PostgreSQL
        name: madmax1
        namespace: platform
    input:
      apiVersion: function-recovery-python.fn.kaonix.com/v1beta1
      kind: Input
      spec:
        mode: cleanup
        target:
          namespace: platform
  - step: resume
    functionRef:
      name: function-pause
    requirements:
      requiredResources:
      - requirementName: target
        apiVersion: database.kaonix.inc.fr/v1alpha1
        kind: PostgreSQL
        name: madmax1
        namespace: platform
    input:
      apiVersion: function-pause.fn.kaonix.com/v1beta1
      kind: Input
      spec:
        target:
          apiVersion: database.kaonix.inc.fr/v1alpha1
          kind: PostgreSQL
          name: madmax1
          namespace: platform
        paused: false