apiVersion: database.kaonix.inc.fr/v1alpha1
kind: DatabaseRestore
metadata:
  name: madmax
  labels:
    recovery.kaonix.inc.fr/trigger: requested
spec:
  backupName: madmax-backup
  target:
    namespace: platform