apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-scale
spec:
  compositeTypeRef:
    apiVersion: kaonix.com/v1alpha1
    kind: App
  mode: Pipeline
  pipeline:
  - step: generate-desired
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: app-deployment
        base:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: my-app
            namespace: platform
          spec:
            replicas: 1
      - name: app-service
        base:
          apiVersion: v1
          kind: Service
          metadata:
            name: my-app-svc
            namespace: platform
          spec:
            type: ClusterIP
  - step: scale
    functionRef:
      name: function-scale
    input:
      apiVersion: function-scale.fn.kaonix.com/v1beta1
      kind: Input
      spec:
        scaleTargets:
        - name: my-app
          replicas: 8